/* Copyright 2011 Google */var tn_=!0,tn_a=null,tn_b=!1;function tn_aa(a){return a in tn_ba?tn_ba[a]:tn_ba[a]=-1!=navigator.userAgent.toLowerCase().indexOf(a)}var tn_ba={},tn_ca={ua:function(a){return a.document.body.scrollTop},va:function(a){return a.document.documentElement.scrollTop},W:function(a){return a.pageYOffset}},tn_da={ua:function(a){return a.document.body.scrollLeft},va:function(a){return a.document.documentElement.scrollLeft},W:function(a){return a.pageXOffset}};
function tn_ea(a,b){try{if(tn_aa("safari")||tn_aa("konqueror"))return b.W(a);if(!window.opera&&"compatMode"in a.document&&"CSS1Compat"==a.document.compatMode)return b.va(a);if(tn_aa("msie")&&!window.opera)return b.ua(a)}catch(c){}return b.W(a)};function tn_c(a,b,c){this.x=a;this.y=b;this.coordinateFrame=c||tn_a}tn_c.prototype.toString=function(){return"[P "+this.x+","+this.y+"]"};tn_c.prototype.clone=function(){return new tn_c(this.x,this.y,this.coordinateFrame)};function tn_fa(a,b){this.dx=a;this.dy=b}tn_fa.prototype.toString=function(){return"[D "+this.dx+","+this.dy+"]"};function tn_d(a,b,c,d,e){this.x=a;this.y=b;this.w=c;this.h=d;this.coordinateFrame=e||tn_a}
tn_d.prototype.contains=function(a){return this.x<=a.x&&a.x<this.x+this.w&&this.y<=a.y&&a.y<this.y+this.h};tn_d.prototype.toString=function(){return"[R "+this.w+"x"+this.h+"+"+this.x+"+"+this.y+"]"};tn_d.prototype.clone=function(){return new tn_d(this.x,this.y,this.w,this.h,this.coordinateFrame)};function tn_ga(a){function b(b){for(var c=a.offsetParent;c&&c.offsetParent;c=c.offsetParent)c.scrollLeft&&(b.x-=c.scrollLeft),c.scrollTop&&(b.y-=c.scrollTop)}if(!a)return tn_a;var c;c=a.ownerDocument&&a.ownerDocument.parentWindow?a.ownerDocument.parentWindow:a.ownerDocument&&a.ownerDocument.defaultView?a.ownerDocument.defaultView:window;if(a.getBoundingClientRect){var d=a.getBoundingClientRect();return new tn_d(d.left+tn_ea(c,tn_da),d.top+tn_ea(c,tn_ca),d.right-d.left,d.bottom-d.top,c)}if(a.ownerDocument&&
a.ownerDocument.getBoxObjectFor)return d=a.ownerDocument.getBoxObjectFor(a),c=new tn_d(d.x,d.y,d.width,d.height,c),b(c),c;for(var e=d=0,f=a;f.offsetParent;f=f.offsetParent)d+=f.offsetLeft,e+=f.offsetTop;c=new tn_d(d,e,a.offsetWidth,a.offsetHeight,c);b(c);return c};var tn_e=function(){for(var a=[" ","\u0120",-1,"!","\u0120",-1,"\u0120","\u0120",0,"\u0121","\u0120",-1,"\u0121","\u0120|\u0121",0,"\u0122","\u0120|\u0121",-1,"\u0120","[\u0120]",0,"\u0121","[\u0120]",-1,"\u0121","[\u0120\u0121]",0,"\u0122","[\u0120\u0121]",-1,"\u0121","[\u0120-\u0121]",0,"\u0122","[\u0120-\u0121]",-1],b=0;b<a.length;b+=3)if(a[b].search(RegExp(a[b+1]))!=a[b+2])return tn_b;return tn_}(),tn_ha=tn_e?"A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u0131\u0134-\u013e\u0141-\u0148\u014a-\u017e\u0180-\u01c3\u01cd-\u01f0\u01f4-\u01f5\u01fa-\u0217\u0250-\u02a8\u02bb-\u02c1\u0386\u0388-\u038a\u038c\u038e-\u03a1\u03a3-\u03ce\u03d0-\u03d6\u03da\u03dc\u03de\u03e0\u03e2-\u03f3\u0401-\u040c\u040e-\u044f\u0451-\u045c\u045e-\u0481\u0490-\u04c4\u04c7-\u04c8\u04cb-\u04cc\u04d0-\u04eb\u04ee-\u04f5\u04f8-\u04f9\u0531-\u0556\u0559\u0561-\u0586\u05d0-\u05ea\u05f0-\u05f2\u0621-\u063a\u0641-\u064a\u0671-\u06b7\u06ba-\u06be\u06c0-\u06ce\u06d0-\u06d3\u06d5\u06e5-\u06e6\u0905-\u0939\u093d\u0958-\u0961\u0985-\u098c\u098f-\u0990\u0993-\u09a8\u09aa-\u09b0\u09b2\u09b6-\u09b9\u09dc-\u09dd\u09df-\u09e1\u09f0-\u09f1\u0a05-\u0a0a\u0a0f-\u0a10\u0a13-\u0a28\u0a2a-\u0a30\u0a32-\u0a33\u0a35-\u0a36\u0a38-\u0a39\u0a59-\u0a5c\u0a5e\u0a72-\u0a74\u0a85-\u0a8b\u0a8d\u0a8f-\u0a91\u0a93-\u0aa8\u0aaa-\u0ab0\u0ab2-\u0ab3\u0ab5-\u0ab9\u0abd\u0ae0\u0b05-\u0b0c\u0b0f-\u0b10\u0b13-\u0b28\u0b2a-\u0b30\u0b32-\u0b33\u0b36-\u0b39\u0b3d\u0b5c-\u0b5d\u0b5f-\u0b61\u0b85-\u0b8a\u0b8e-\u0b90\u0b92-\u0b95\u0b99-\u0b9a\u0b9c\u0b9e-\u0b9f\u0ba3-\u0ba4\u0ba8-\u0baa\u0bae-\u0bb5\u0bb7-\u0bb9\u0c05-\u0c0c\u0c0e-\u0c10\u0c12-\u0c28\u0c2a-\u0c33\u0c35-\u0c39\u0c60-\u0c61\u0c85-\u0c8c\u0c8e-\u0c90\u0c92-\u0ca8\u0caa-\u0cb3\u0cb5-\u0cb9\u0cde\u0ce0-\u0ce1\u0d05-\u0d0c\u0d0e-\u0d10\u0d12-\u0d28\u0d2a-\u0d39\u0d60-\u0d61\u0e01-\u0e2e\u0e30\u0e32-\u0e33\u0e40-\u0e45\u0e81-\u0e82\u0e84\u0e87-\u0e88\u0e8a\u0e8d\u0e94-\u0e97\u0e99-\u0e9f\u0ea1-\u0ea3\u0ea5\u0ea7\u0eaa-\u0eab\u0ead-\u0eae\u0eb0\u0eb2-\u0eb3\u0ebd\u0ec0-\u0ec4\u0f40-\u0f47\u0f49-\u0f69\u10a0-\u10c5\u10d0-\u10f6\u1100\u1102-\u1103\u1105-\u1107\u1109\u110b-\u110c\u110e-\u1112\u113c\u113e\u1140\u114c\u114e\u1150\u1154-\u1155\u1159\u115f-\u1161\u1163\u1165\u1167\u1169\u116d-\u116e\u1172-\u1173\u1175\u119e\u11a8\u11ab\u11ae-\u11af\u11b7-\u11b8\u11ba\u11bc-\u11c2\u11eb\u11f0\u11f9\u1e00-\u1e9b\u1ea0-\u1ef9\u1f00-\u1f15\u1f18-\u1f1d\u1f20-\u1f45\u1f48-\u1f4d\u1f50-\u1f57\u1f59\u1f5b\u1f5d\u1f5f-\u1f7d\u1f80-\u1fb4\u1fb6-\u1fbc\u1fbe\u1fc2-\u1fc4\u1fc6-\u1fcc\u1fd0-\u1fd3\u1fd6-\u1fdb\u1fe0-\u1fec\u1ff2-\u1ff4\u1ff6-\u1ffc\u2126\u212a-\u212b\u212e\u2180-\u2182\u3041-\u3094\u30a1-\u30fa\u3105-\u312c\uac00-\ud7a3":
"A-Za-z",tn_ia=tn_e?"\u4e00-\u9fa5\u3007\u3021-\u3029":"",tn_ja=tn_e?"\u0300-\u0345\u0360-\u0361\u0483-\u0486\u0591-\u05a1\u05a3-\u05b9\u05bb-\u05bd\u05bf\u05c1-\u05c2\u05c4\u064b-\u0652\u0670\u06d6-\u06dc\u06dd-\u06df\u06e0-\u06e4\u06e7-\u06e8\u06ea-\u06ed\u0901-\u0903\u093c\u093e-\u094c\u094d\u0951-\u0954\u0962-\u0963\u0981-\u0983\u09bc\u09be\u09bf\u09c0-\u09c4\u09c7-\u09c8\u09cb-\u09cd\u09d7\u09e2-\u09e3\u0a02\u0a3c\u0a3e\u0a3f\u0a40-\u0a42\u0a47-\u0a48\u0a4b-\u0a4d\u0a70-\u0a71\u0a81-\u0a83\u0abc\u0abe-\u0ac5\u0ac7-\u0ac9\u0acb-\u0acd\u0b01-\u0b03\u0b3c\u0b3e-\u0b43\u0b47-\u0b48\u0b4b-\u0b4d\u0b56-\u0b57\u0b82-\u0b83\u0bbe-\u0bc2\u0bc6-\u0bc8\u0bca-\u0bcd\u0bd7\u0c01-\u0c03\u0c3e-\u0c44\u0c46-\u0c48\u0c4a-\u0c4d\u0c55-\u0c56\u0c82-\u0c83\u0cbe-\u0cc4\u0cc6-\u0cc8\u0cca-\u0ccd\u0cd5-\u0cd6\u0d02-\u0d03\u0d3e-\u0d43\u0d46-\u0d48\u0d4a-\u0d4d\u0d57\u0e31\u0e34-\u0e3a\u0e47-\u0e4e\u0eb1\u0eb4-\u0eb9\u0ebb-\u0ebc\u0ec8-\u0ecd\u0f18-\u0f19\u0f35\u0f37\u0f39\u0f3e\u0f3f\u0f71-\u0f84\u0f86-\u0f8b\u0f90-\u0f95\u0f97\u0f99-\u0fad\u0fb1-\u0fb7\u0fb9\u20d0-\u20dc\u20e1\u302a-\u302f\u3099\u309a":
"",tn_ka=tn_e?"0-9\u0660-\u0669\u06f0-\u06f9\u0966-\u096f\u09e6-\u09ef\u0a66-\u0a6f\u0ae6-\u0aef\u0b66-\u0b6f\u0be7-\u0bef\u0c66-\u0c6f\u0ce6-\u0cef\u0d66-\u0d6f\u0e50-\u0e59\u0ed0-\u0ed9\u0f20-\u0f29":"0-9",tn_la=tn_e?"\u00b7\u02d0\u02d1\u0387\u0640\u0e46\u0ec6\u3005\u3031-\u3035\u309d-\u309e\u30fc-\u30fe":"",tn_ma=tn_ha+tn_ia,tn_na=tn_ma+tn_ka+"\\._:"+tn_ja+tn_la+"-",tn_oa="["+tn_ma+"_:]["+tn_na+"]*",tn_pa="&"+tn_oa+";",tn_qa=tn_pa+"|&#[0-9]+;|&#x[0-9a-fA-F]+;",tn_ra='"(([^<&"]|'+tn_qa+")*)\"|'(([^<&']|"+
tn_qa+")*)'",tn_sa="("+tn_oa+")([ \t\r\n]+)?=([ \t\r\n]+)?("+tn_ra+")",tn_ta=tn_e?":A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd":":A-Z_a-z",tn_ua=tn_ta+(tn_e?"\\.0-9\u00b7\u0300-\u036f\u203f-\u2040-":"\\.0-9-"),tn_va="["+tn_ta+"]["+tn_ua+"]*",tn_wa="&"+tn_va+";",tn_xa=tn_wa+"|&#[0-9]+;|&#x[0-9a-fA-F]+;",tn_ya='"(([^<&"]|'+tn_xa+")*)\"|'(([^<&']|"+tn_xa+")*)'",tn_za="("+tn_va+")([ \t\r\n]+)?=([ \t\r\n]+)?("+
tn_ya+")",tn_Aa=tn_ma+tn_ka+"\\._"+tn_ja+tn_la+"-",tn_Ba="["+tn_ma+"_]["+tn_Aa+"]*";function tn_f(a){a||tn_g("Assertion failed")}function tn_Ca(a,b){var c=a.indexOf(b);if(-1==c)return[a];var d=[];for(d.push(a.substr(0,c));-1!=c;){var e=a.indexOf(b,c+1);-1!=e?d.push(a.substr(c+1,e-c-1)):d.push(a.substr(c+1));c=e}return d}
function tn_Da(a,b){if(3==b.nodeType)return a.createTextNode(b.nodeValue);if(4==b.nodeType)return a.createCDATASection(b.nodeValue);if(1==b.nodeType){for(var c=a.createElement(b.nodeName),d=0;d<b.attributes.length;++d){var e=b.attributes[d],f=e.nodeName,e=e.nodeValue;c.setAttribute(f,e)}for(d=b.firstChild;d;d=d.nextSibling)f=arguments.callee(a,d),c.appendChild(f);return c}return a.createComment(b.nodeName)}function tn_Ea(){this.keys=[]}tn_Ea.prototype.size=function(){return this.keys.length};
tn_Ea.prototype.add=function(a,b){var c=b||1;this.contains(a)||(this[":"+a]=c,this.keys.push(a))};tn_Ea.prototype.remove=function(a){this.contains(a)&&(delete this[":"+a],tn_Fa(this.keys,a,tn_))};tn_Ea.prototype.contains=function(a){return"undefined"!=typeof this[":"+a]};tn_Ea.prototype.map=function(a){for(var b=0;b<this.keys.length;++b){var c=this.keys[b];a.call(this,c,this[":"+c])}};
tn_Ea.prototype.clear=function(){for(var a=0;a<this.keys.length;++a)delete this[":"+this.keys[a]];this.keys.length=0};function tn_Ga(a,b){for(var c=0;c<a.length;++c)b.call(this,a[c],c)}function tn_Ha(a,b){for(var c=[],d=0;d<a.length;++d)c.push(b(a[d]));return c}function tn_Ia(a){for(var b=0;b<a.length/2;++b){var c=a[b],d=a.length-b-1;a[b]=a[d];a[d]=c}}function tn_Fa(a,b,c){for(var d=0,e=0;e<a.length;++e)if(a[e]===b||c&&a[e]==b)a.splice(e--,1),d++;return d}
function tn_Ja(a,b){for(var c=0;c<b.length;++c)a.push(b[c])}function tn_h(a){if(!a)return"";var b="";if(3==a.nodeType||4==a.nodeType||2==a.nodeType)b+=a.nodeValue;else if(1==a.nodeType||9==a.nodeType||11==a.nodeType)for(var c=0;c<a.childNodes.length;++c)b+=arguments.callee(a.childNodes[c]);return b}function tn_Ka(a,b){var c=[];tn_La(a,c,b);return c.join("")}
function tn_La(a,b,c){if(3==a.nodeType)b.push(tn_Ma(a.nodeValue));else if(4==a.nodeType)c?b.push(a.nodeValue):b.push("<![CDATA["+a.nodeValue+"]]\x3e");else if(8==a.nodeType)b.push("\x3c!--"+a.nodeValue+"--\x3e");else if(1==a.nodeType){b.push("<"+tn_Na(a));for(var d=0;d<a.attributes.length;++d){var e=a.attributes[d];e&&(e.nodeName&&e.nodeValue)&&b.push(" "+tn_Na(e)+'="'+tn_Ma(e.nodeValue).replace(/\"/g,"&quot;")+'"')}if(0==a.childNodes.length)b.push("/>");else{b.push(">");for(d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],
b,c);b.push("</"+tn_Na(a)+">")}}else if(9==a.nodeType||11==a.nodeType)for(d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],b,c)}function tn_Na(a){return a.prefix&&0!=a.nodeName.indexOf(a.prefix+":")?a.prefix+":"+a.nodeName:a.nodeName}function tn_Ma(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function tn_Oa(a,b,c){return a.setAttribute(b,c)}function tn_Pa(a,b){return a.appendChild(b)}function tn_Qa(a,b){return a.createTextNode(b)}
function tn_g(a){if("undefined"!=typeof Error)throw Error(a||"Assertion Failed");throw a;};function tn_Ra(a){a=tn_Ca(a,"&");for(var b=a[0],c=1;c<a.length;++c){var d=a[c].indexOf(";");if(-1==d)b+=a[c];else{var e=a[c].substring(0,d),d=a[c].substring(d+1);switch(e){case "lt":e="<";break;case "gt":e=">";break;case "amp":e="&";break;case "quot":e='"';break;case "apos":e="'";break;case "nbsp":e=String.fromCharCode(160);break;default:var f=window.document.createElement("span");f.innerHTML="&"+e+"; ";e=f.childNodes[0].nodeValue.charAt(0)}b+=e+d}}return b}
var tn_Sa=RegExp("^("+tn_oa+")"),tn_Ta=RegExp(tn_sa,"g"),tn_Ua=RegExp("^("+tn_va+")"),tn_Va=RegExp(tn_za,"g");
function tn_Wa(a){var b=/\/$/,c,d;a.match(/^<\?xml/)?5==a.search(/[ \t\r\n]+version([ \t\r\n]+)?=([ \t\r\n]+)?("1\.0"|'1\.0')/)?(c=tn_Sa,d=tn_Ta):5==a.search(/[ \t\r\n]+version([ \t\r\n]+)?=([ \t\r\n]+)?("1\.1"|'1\.1')/)?(c=tn_Ua,d=tn_Va):alert("VersionInfo is missing, or unknown version number."):(c=tn_Sa,d=tn_Ta);var e=new tn_i,f=e,h=[],j=f;h.push(j);var m="";a=tn_Ca(a,"<");for(var k=1;k<a.length;++k){var g=tn_Ca(a[k],">"),i=g[0],g=tn_Ra(g[1]||"");if(m)if(i=a[k].indexOf(m),-1!=i){var n=a[k].substring(0,
i);j.nodeValue+="<"+n;h.pop();j=h[h.length-1];g=a[k].substring(i+m.length);m=""}else j.nodeValue+="<"+a[k],g=tn_a;else if(0==i.indexOf("![CDATA["))if(n=8,i=a[k].indexOf("]]\x3e"),-1!=i){var n=a[k].substring(n,i),l=e.createCDATASection(n);j.appendChild(l)}else n=a[k].substring(n),g=tn_a,l=e.createCDATASection(n),j.appendChild(l),j=l,h.push(l),m="]]\x3e";else if(0==i.indexOf("!--"))n=3,i=a[k].indexOf("--\x3e"),-1!=i?(n=a[k].substring(n,i),l=e.createComment(n),j.appendChild(l)):(n=a[k].substring(n),
g=tn_a,l=e.createComment(n),j.appendChild(l),j=l,h.push(l),m="--\x3e");else if("/"==i.charAt(0))h.pop(),j=h[h.length-1];else if("?"!=i.charAt(0)&&"!"!=i.charAt(0)){for(var n=i.match(b),l=c.exec(i)[1],l=e.createElement(l),q;q=d.exec(i);){var p=tn_Ra(q[5]||q[7]||"");l.setAttribute(q[1],p)}j.appendChild(l);n||(j=l,h.push(l))}g&&j!=f&&tn_Pa(j,e.createTextNode(g))}return f}
function tn_Xa(a,b,c){var d;if(b&&(d=b.call(tn_a,a),"boolean"==typeof d&&!d))return tn_b;for(var e=a.firstChild;e;e=e.nextSibling)if(1==e.nodeType&&(d=arguments.callee.call(this,e,b,c),"boolean"==typeof d&&!d))return tn_b;if(c&&(d=c.call(tn_a,a),"boolean"==typeof d&&!d))return tn_b}function tn_j(a,b,c,d){this.attributes=[];this.childNodes=[];tn_j.init.call(this,a,b,c,d)}
tn_j.init=function(a,b,c,d){this.nodeType=a-0;this.nodeName=""+b;this.nodeValue=""+c;this.ownerDocument=d;this.parentNode=this.previousSibling=this.nextSibling=this.lastChild=this.firstChild=tn_a};tn_j.ia=[];
tn_j.recycle=function(a){if(a)if(a.constructor==tn_i)tn_j.recycle(a.documentElement);else if(a.constructor==this){tn_j.ia.push(a);for(var b=0;b<a.attributes.length;++b)tn_j.recycle(a.attributes[b]);for(b=0;b<a.childNodes.length;++b)tn_j.recycle(a.childNodes[b]);a.attributes.length=0;a.childNodes.length=0;tn_j.init.call(a,0,"","",tn_a)}};tn_j.create=function(a,b,c,d){if(0<tn_j.ia.length){var e=tn_j.ia.pop();tn_j.init.call(e,a,b,c,d);return e}return new tn_j(a,b,c,d)};
tn_j.prototype.appendChild=function(a){0==this.childNodes.length&&(this.firstChild=a);a.previousSibling=this.lastChild;a.nextSibling=tn_a;this.lastChild&&(this.lastChild.nextSibling=a);a.parentNode=this;this.lastChild=a;this.childNodes.push(a)};
tn_j.prototype.replaceChild=function(a,b){if(b!=a)for(var c=0;c<this.childNodes.length;++c)if(this.childNodes[c]==b){this.childNodes[c]=a;c=b.parentNode;b.parentNode=tn_a;a.parentNode=c;c=b.previousSibling;b.previousSibling=tn_a;a.previousSibling=c;a.previousSibling&&(a.previousSibling.nextSibling=a);c=b.nextSibling;b.nextSibling=tn_a;a.nextSibling=c;a.nextSibling&&(a.nextSibling.previousSibling=a);this.firstChild==b&&(this.firstChild=a);this.lastChild==b&&(this.lastChild=a);break}};
tn_j.prototype.insertBefore=function(a,b){if(b!=a&&b.parentNode==this){a.parentNode&&a.parentNode.removeChild(a);for(var c=[],d=0;d<this.childNodes.length;++d){var e=this.childNodes[d];e==b&&(c.push(a),a.parentNode=this,a.previousSibling=b.previousSibling,b.previousSibling=a,a.previousSibling&&(a.previousSibling.nextSibling=a),a.nextSibling=b,this.firstChild==b&&(this.firstChild=a));c.push(e)}this.childNodes=c}};
tn_j.prototype.removeChild=function(a){for(var b=[],c=0;c<this.childNodes.length;++c){var d=this.childNodes[c];d!=a?b.push(d):(d.previousSibling&&(d.previousSibling.nextSibling=d.nextSibling),d.nextSibling&&(d.nextSibling.previousSibling=d.previousSibling),this.firstChild==d&&(this.firstChild=d.nextSibling),this.lastChild==d&&(this.lastChild=d.previousSibling))}this.childNodes=b};tn_j.prototype.hasAttributes=function(){return 0<this.attributes.length};
tn_j.prototype.setAttribute=function(a,b){for(var c=0;c<this.attributes.length;++c)if(this.attributes[c].nodeName==a){this.attributes[c].nodeValue=""+b;return}this.attributes.push(tn_j.create(2,a,b,this))};tn_j.prototype.getAttribute=function(a){for(var b=0;b<this.attributes.length;++b)if(this.attributes[b].nodeName==a)return this.attributes[b].nodeValue;return tn_a};
tn_j.prototype.removeAttribute=function(a){for(var b=[],c=0;c<this.attributes.length;++c)this.attributes[c].nodeName!=a&&b.push(this.attributes[c]);this.attributes=b};tn_j.prototype.getElementsByTagName=function(a){var b=[];tn_Xa(this,function(c){c.nodeName==a&&b.push(c)},tn_a);return b};tn_j.prototype.getElementById=function(a){var b=tn_a;tn_Xa(this,function(c){if(c.getAttribute("id")==a)return b=c,tn_b},tn_a);return b};
function tn_i(){tn_j.call(this,9,"#document",tn_a,tn_a);this.documentElement=tn_a}tn_i.prototype=new tn_j(9,"#document");tn_i.prototype.clear=function(){tn_j.recycle(this.documentElement);this.documentElement=tn_a};tn_i.prototype.appendChild=function(a){tn_j.prototype.appendChild.call(this,a);this.documentElement=this.childNodes[0]};tn_i.prototype.createElement=function(a){return tn_j.create(1,a,tn_a,this)};
tn_i.prototype.createDocumentFragment=function(){return tn_j.create(11,"#document-fragment",tn_a,this)};tn_i.prototype.createTextNode=function(a){return tn_j.create(3,"#text",a,this)};tn_i.prototype.createAttribute=function(a){return tn_j.create(2,a,tn_a,this)};tn_i.prototype.createComment=function(a){return tn_j.create(8,"#comment",a,this)};tn_i.prototype.createCDATASection=function(a){return tn_j.create(4,"#cdata-section",a,this)};function tn_Ya(a,b){tn_Za(new tn_k(a,b),b)}
function tn_Za(a,b){var c=b.getAttribute("select");if(c)b.removeAttribute("select"),tn__a(a,b,c);else{if(c=b.getAttribute("display"))if(tn_0a(c,a).d())b.removeAttribute("display");else{b.parentNode.removeChild(b);return}if(c=b.getAttribute("values"))b.removeAttribute("values"),tn_1a(a,b,c);if(c=b.getAttribute("transclude"))(c=tn_2a(c,b.ownerDocument))?(b.parentNode.replaceChild(c,b),tn_Za(a,c)):b.parentNode.removeChild(b),tn_j.recycle(b);else if(c=b.getAttribute("content"))b.removeAttribute("content"),tn_3a(a,
b,c);else{for(var c=[],d=0;d<b.childNodes.length;++d)1==b.childNodes[d].nodeType&&c.push(b.childNodes[d]);for(d=0;d<c.length;++d)tn_Za(a,c[d])}}}
function tn__a(a,b,c){var d=c.split(/;/),e=tn_0a(d[0],a).c();if(0<e.length){c=[];for(var f=1;f<e.length;++f){var h=tn_Da(b.ownerDocument,b);c.push(h);b.parentNode.insertBefore(h,b)}c.push(b);b=[];for(f=1;f<d.length;++f){var j=d[f],m=0;"#"==j.charAt(m)?(h="number",m++):h="text";"-"==j.charAt(m)?(j="descending",m++):j="ascending";m=tn_4a(d[f].substr(m));b.push({expr:m,type:h,order:j})}a=a.clone(e[0],0,e);tn_5a(a,b);for(f=0;f<a.z();++f)1==a.nodelist[f].nodeType&&tn_Za(a.clone(a.nodelist[f],f),c[f])}else b.parentNode.removeChild(b)}
function tn_1a(a,b,c){c=c.split(/;/);for(var d=0;d<c.length;++d){var e=c[d].indexOf(":");if(!(0>e)){var f=c[d].substr(0,e),e=tn_0a(c[d].substr(e+1),a);"$"==f.charAt(0)?a.fa(f.substr(1),e):f&&tn_Oa(b,f,e.a())}}}
function tn_3a(a,b,c){for(;b.firstChild;)b.removeChild(b.firstChild);a=tn_0a(c,a);if("node-set"==a.type)for(c=0;c<a.value.length;++c){var d=a.value[c];if(1==d.nodeType)for(d=d.firstChild;d;d=d.nextSibling){var e=tn_Da(b.ownerDocument,d);b.appendChild(e)}else 2==d.nodeType&&(d=b.ownerDocument.createTextNode(d.nodeValue),b.appendChild(d))}else d=tn_Qa(b.ownerDocument,a.a()),b.appendChild(d)}function tn_0a(a,b){var c=tn_4a(a);return c=c.evaluate(b)}
function tn_2a(a,b){var c=b.getElementById(a);return c?c=tn_Da(b,c):tn_a};function tn_4a(a){tn_6a();var b=tn_7a[a];if(b)return b;if(a.match(/^(\$|@)?\w+$/i))return b=tn_8a(a),tn_7a[a]=b;if(a.match(/^\w+(\/\w+)*$/i))return b=tn_9a(a),tn_7a[a]=b;for(var b=a,c=[],d=tn_a,e=tn_a,f=tn_b,h=0,j=0,m=0;!f;){h++;a=a.replace(/^\s*/,"");for(var e=d,k=d=tn_a,g="",i=0;i<tn_$a.length;++i){var n=tn_$a[i].re.exec(a);j++;if(n&&0<n.length&&n[0].length>g.length){k=tn_$a[i];g=n[0];break}}if(k&&(k==tn_ab||k==tn_bb||k==tn_cb||k==tn_db)&&(!e||e.tag==tn_eb||e.tag==tn_fb||e.tag==tn_l||e.tag==tn_gb||
e.tag==tn_hb))k=tn_ib;k?(a=a.substr(g.length),d={tag:k,match:g,prec:k.prec?k.prec:0,expr:new tn_jb(g)}):f=tn_;for(;tn_kb(c,d);)m++}1!=c.length&&tn_g("XPath parse error "+b+":\n"+tn_lb(c));n=c[0].expr;return tn_7a[b]=n}var tn_7a={};
function tn_kb(a,b){var c=tn_a;if(0<a.length){var d=a[a.length-1];if(d=tn_mb[d.tag.key])for(var e=0;e<d.length;++e){var f=d[e],h=tn_nb(a,f[1]);if(h.length){c={tag:f[0],rule:f,match:h};c.prec=tn_ob(c);break}}}if(c&&(!b||c.prec>b.prec||b.tag.left&&c.prec>=b.prec)){for(e=0;e<c.match.matchlength;++e)a.pop();d=tn_Ha(c.match,function(a){return a.expr});c.expr=c.rule[3].apply(tn_a,d);a.push(c);c=tn_}else b&&a.push(b),c=tn_b;return c}
function tn_nb(a,b){for(var c=a.length,d=b.length,e=[],f=e.matchlength=0,d=d-1,c=c-1;0<=d&&0<=c;--d,c-=f){var f=0,h=[];if(b[d]==tn_pb){d-=1;for(e.push(h);0<=c-f&&a[c-f].tag==b[d];)h.push(a[c-f]),f+=1,e.matchlength+=1}else if(b[d]==tn_qb){d-=1;for(e.push(h);0<=c-f&&2>f&&a[c-f].tag==b[d];)h.push(a[c-f]),f+=1,e.matchlength+=1}else if(b[d]==tn_rb)if(d-=1,e.push(h),a[c].tag==b[d])for(;0<=c-f&&a[c-f].tag==b[d];)h.push(a[c-f]),f+=1,e.matchlength+=1;else return[];else if(a[c].tag==b[d])e.push(a[c]),f+=1,
e.matchlength+=1;else return[];tn_Ia(h);h.expr=tn_Ha(h,function(a){return a.expr})}tn_Ia(e);return-1==d?e:[]}function tn_ob(a){var b=0;if(a.rule)if(3<=a.rule.length&&0<=a.rule[2])b=a.rule[2];else for(var c=0;c<a.rule[1].length;++c)var d=a.rule[1][c].prec||2,b=Math.max(b,d);else if(a.tag)b=a.tag.prec||2;else if(a.length)for(c=0;c<a.length;++c)d=tn_ob(a[c]),b=Math.max(b,d);return b}function tn_lb(a){for(var b="",c=0;c<a.length;++c)b&&(b+="\n"),b+=a[c].tag.label;return b}
function tn_k(a,b,c,d,e){this.node=a;this.stylesheet=b||tn_a;this.position=c||0;this.nodelist=d||[a];this.variables={};this.parent=e||tn_a;this.root=e?e.root:9==this.node.nodeType?a:a.ownerDocument}tn_k.prototype.clone=function(a,b,c){return new tn_k(a||this.node,this.stylesheet,"undefined"!=typeof b?b:this.position,c||this.nodelist,this)};tn_k.prototype.fa=function(a,b){this.variables[a]=b};
tn_k.prototype.J=function(a){return"undefined"!=typeof this.variables[a]?this.variables[a]:this.parent?this.parent.J(a):tn_a};tn_k.prototype.Oa=function(a){this.node=this.nodelist[a];this.position=a};tn_k.prototype.z=function(){return this.nodelist.length};function tn_m(a){this.value=a;this.type="string"}tn_m.prototype.a=function(){return this.value};tn_m.prototype.d=function(){return 0<this.value.length};tn_m.prototype.b=function(){return this.value-0};tn_m.prototype.c=function(){tn_g(this)};
function tn_n(a){this.value=a;this.type="boolean"}tn_n.prototype.a=function(){return""+this.value};tn_n.prototype.d=function(){return this.value};tn_n.prototype.b=function(){return this.value?1:0};tn_n.prototype.c=function(){tn_g(this)};function tn_o(a){this.value=a;this.type="number"}tn_o.prototype.a=function(){return""+this.value};tn_o.prototype.d=function(){return!!this.value};tn_o.prototype.b=function(){return this.value-0};tn_o.prototype.c=function(){tn_g(this)};
function tn_p(a){this.value=a;this.type="node-set"}tn_p.prototype.a=function(){return 0==this.value.length?"":tn_h(this.value[0])};tn_p.prototype.d=function(){return 0<this.value.length};tn_p.prototype.b=function(){return this.a()-0};tn_p.prototype.c=function(){return this.value};function tn_jb(a){this.value=a}tn_jb.prototype.evaluate=function(){return new tn_m(this.value)};function tn_q(){this.absolute=tn_b;this.rootExpr=tn_a;this.steps=[]}tn_q.prototype.k=function(a){this.steps.push(a)};
tn_q.prototype.ca=function(a){this.steps.unshift(a)};tn_q.prototype.evaluate=function(a){var b;b=this.rootExpr?this.rootExpr.evaluate(a).c():this.absolute?[a.root]:[a.node];for(var c=[],d=0;d<b.length;++d){var e=b[d];tn_sb(c,this.steps,0,e,a)}return new tn_p(c)};function tn_sb(a,b,c,d,e){var f=b[c];d=e.clone(d);f=f.evaluate(d).c();for(d=0;d<f.length;++d)c==b.length-1?a.push(f[d]):tn_sb(a,b,c+1,f[d],e)}function tn_r(a,b,c){this.axis=a;this.nodetest=b;this.predicate=c||[]}tn_r.prototype.la=function(a){this.predicate.push(a)};
tn_r.prototype.evaluate=function(a){var b=a.node,c=[];if(this.axis==tn_s.ANCESTOR_OR_SELF){c.push(b);for(b=b.parentNode;b;b=b.parentNode)c.push(b)}else if(this.axis==tn_s.ANCESTOR)for(b=b.parentNode;b;b=b.parentNode)c.push(b);else if(this.axis==tn_s.ATTRIBUTE)tn_Ja(c,b.attributes);else if(this.axis==tn_s.CHILD)tn_Ja(c,b.childNodes);else if(this.axis==tn_s.DESCENDANT_OR_SELF)c.push(b),tn_tb(c,b);else if(this.axis==tn_s.DESCENDANT)tn_tb(c,b);else if(this.axis==tn_s.FOLLOWING)for(;b;b=b.parentNode)for(var d=
b.nextSibling;d;d=d.nextSibling)c.push(d),tn_tb(c,d);else if(this.axis==tn_s.FOLLOWING_SIBLING)for(b=b.nextSibling;b;b=b.nextSibling)c.push(b);else if(this.axis==tn_s.NAMESPACE)tn_g("not implemented: axis namespace");else if(this.axis==tn_s.PARENT)b.parentNode&&c.push(b.parentNode);else if(this.axis==tn_s.PRECEDING)for(;b;b=b.parentNode)for(d=b.previousSibling;d;d=d.previousSibling)c.push(d),tn_ub(c,d);else if(this.axis==tn_s.PRECEDING_SIBLING)for(b=b.previousSibling;b;b=b.previousSibling)c.push(b);
else this.axis==tn_s.SELF?c.push(b):tn_g("ERROR -- NO SUCH AXIS: "+this.axis);for(var d=c,c=[],e=0;e<d.length;++e)b=d[e],this.nodetest.evaluate(a.clone(b,e,d)).d()&&c.push(b);for(e=0;e<this.predicate.length;++e)for(var d=c,c=[],f=0;f<d.length;++f)b=d[f],this.predicate[e].evaluate(a.clone(b,f,d)).d()&&c.push(b);return new tn_p(c)};function tn_vb(){this.value=new tn_n(tn_)}tn_vb.prototype.evaluate=function(){return this.value};function tn_wb(){}
tn_wb.prototype.evaluate=function(a){return new tn_n(1==a.node.nodeType||2==a.node.nodeType)};function tn_xb(){}tn_xb.prototype.evaluate=function(a){return new tn_n(3==a.node.nodeType)};function tn_yb(){}tn_yb.prototype.evaluate=function(a){return new tn_n(8==a.node.nodeType)};function tn_zb(a){this.target=a}tn_zb.prototype.evaluate=function(a){return new tn_n(7==a.node.nodeType&&(!this.target||a.node.nodeName==this.target))};function tn_Ab(a){this.regex=RegExp("^"+a+":");this.nsprefix=a}
tn_Ab.prototype.evaluate=function(a){a=a.node;return new tn_n(this.regex.test(a.nodeName))};function tn_Bb(a){this.name=a}tn_Bb.prototype.evaluate=function(a){a=a.node;return new tn_n(a.nodeName==this.name)};function tn_Cb(a){this.expr=a}tn_Cb.prototype.evaluate=function(a){var b=this.expr.evaluate(a);return"number"==b.type?new tn_n(a.position==b.b()-1):new tn_n(b.d())};function tn_Db(a){this.name=a;this.args=[]}tn_Db.prototype.T=function(a){this.args.push(a)};
tn_Db.prototype.evaluate=function(a){var b=""+this.name.value;return(b=this.xpathfunctions[b])?b.call(this,a):new tn_n(tn_b)};
tn_Db.prototype.xpathfunctions={last:function(a){tn_f(0==this.args.length);return new tn_o(a.z())},position:function(a){tn_f(0==this.args.length);return new tn_o(a.position+1)},count:function(a){tn_f(1==this.args.length);a=this.args[0].evaluate(a);return new tn_o(a.c().length)},id:function(a){tn_f(1==this.args.length);var b=this.args[0].evaluate(a),c=[],d;if("node-set"==b.type){d=[];for(var e=b.c(),b=0;b<e.length;++b)for(var f=tn_h(e[b]).split(/\s+/),h=0;h<f.length;++h)d.push(f[h])}else d=b.a().split(/\s+/);
a=a.node.ownerDocument;for(b=0;b<d.length;++b)(e=a.getElementById(d[b]))&&c.push(e);return new tn_p(c)},"local-name":function(){tn_g("not implmented yet: XPath function local-name()")},"namespace-uri":function(){tn_g("not implmented yet: XPath function namespace-uri()")},name:function(a){tn_f(1==this.args.length||0==this.args.length);a=0==this.args.length?[a.node]:this.args[0].evaluate(a).c();return 0==a.length?new tn_m(""):new tn_m(a[0].nodeName)},string:function(a){tn_f(1==this.args.length||0==
this.args.length);return 0==this.args.length?new tn_m((new tn_p([a.node])).a()):new tn_m(this.args[0].evaluate(a).a())},concat:function(a){for(var b="",c=0;c<this.args.length;++c)b+=this.args[c].evaluate(a).a();return new tn_m(b)},document:function(a){var b=this.args[0].evaluate(a).a();if(""===b&&a.stylesheet)return new tn_p([a.stylesheet]);tn_g("Can't resolve uri in document(\""+b+'")')},"starts-with":function(a){tn_f(2==this.args.length);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();
return new tn_n(0==b.indexOf(a))},contains:function(a){tn_f(2==this.args.length);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();return new tn_n(-1!=b.indexOf(a))},"substring-before":function(a){tn_f(2==this.args.length);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();a=b.indexOf(a);b=-1==a?"":b.substr(0,a);return new tn_m(b)},"substring-after":function(a){tn_f(2==this.args.length);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();var c=b.indexOf(a),
b=-1==c?"":b.substr(c+a.length);return new tn_m(b)},substring:function(a){tn_f(2==this.args.length||3==this.args.length);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).b();if(2==this.args.length)c=Math.max(0,Math.round(c)-1),b=b.substr(c);else{a=this.args[2].evaluate(a).b();var d=Math.round(c)-1,c=Math.max(0,d);a=Math.round(a)-Math.max(0,-d);b=b.substr(c,a)}return new tn_m(b)},"string-length":function(a){a=0<this.args.length?this.args[0].evaluate(a).a():(new tn_p([a.node])).a();return new tn_o(a.length)},
"normalize-space":function(a){a=0<this.args.length?this.args[0].evaluate(a).a():(new tn_p([a.node])).a();a=a.replace(/^\s*/,"").replace(/\s*$/,"").replace(/\s+/g," ");return new tn_m(a)},translate:function(a){tn_f(3==this.args.length);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).a();a=this.args[2].evaluate(a).a();for(var d=0;d<c.length;++d)b=b.replace(RegExp(c.charAt(d),"g"),a.charAt(d));return new tn_m(b)},"boolean":function(a){tn_f(1==this.args.length);return new tn_n(this.args[0].evaluate(a).d())},
not:function(a){tn_f(1==this.args.length);a=!this.args[0].evaluate(a).d();return new tn_n(a)},"true":function(){tn_f(0==this.args.length);return new tn_n(tn_)},"false":function(){tn_f(0==this.args.length);return new tn_n(tn_b)},lang:function(a){tn_f(1==this.args.length);var b=this.args[0].evaluate(a).a(),c;for(a=a.node;a&&a!=a.parentNode&&!(c=a.getAttribute("xml:lang"));)a=a.parentNode;return c?(b=RegExp("^"+b+"$","i"),new tn_n(b.test(c)||b.test(c.replace(/_.*$/,"")))):new tn_n(tn_b)},number:function(a){tn_f(1==
this.args.length||0==this.args.length);return 1==this.args.length?new tn_o(this.args[0].evaluate(a).b()):new tn_o((new tn_p([a.node])).b())},sum:function(a){tn_f(1==this.args.length);a=this.args[0].evaluate(a).c();for(var b=0,c=0;c<a.length;++c)b+=tn_h(a[c])-0;return new tn_o(b)},floor:function(a){tn_f(1==this.args.length);a=this.args[0].evaluate(a).b();return new tn_o(Math.floor(a))},ceiling:function(a){tn_f(1==this.args.length);a=this.args[0].evaluate(a).b();return new tn_o(Math.ceil(a))},round:function(a){tn_f(1==
this.args.length);a=this.args[0].evaluate(a).b();return new tn_o(Math.round(a))},"ext-join":function(a){tn_f(2==this.args.length);var b=this.args[0].evaluate(a).c();a=this.args[1].evaluate(a).a();for(var c="",d=0;d<b.length;++d)c&&(c+=a),c+=tn_h(b[d]);return new tn_m(c)},"ext-if":function(a){tn_f(3==this.args.length);return this.args[0].evaluate(a).d()?this.args[1].evaluate(a):this.args[2].evaluate(a)},"ext-cardinal":function(a){tn_f(1<=this.args.length);for(var b=this.args[0].evaluate(a).b(),c=[],
d=0;d<b;++d)c.push(a.node);return new tn_p(c)}};function tn_Eb(a,b){this.expr1=a;this.expr2=b}tn_Eb.prototype.evaluate=function(a){var b=this.expr1.evaluate(a).c();a=this.expr2.evaluate(a).c();for(var c=b.length,d=0;d<a.length;++d){for(var e=a[d],f=tn_b,h=0;h<c;++h)b[h]==e&&(f=tn_,h=c);f||b.push(e)}return new tn_p(b)};function tn_Fb(a,b){this.filter=a;this.rel=b}
tn_Fb.prototype.evaluate=function(a){for(var b=this.filter.evaluate(a).c(),c=[],d=0;d<b.length;++d)for(var e=this.rel.evaluate(a.clone(b[d],d,b)).c(),f=0;f<e.length;++f)c.push(e[f]);return new tn_p(c)};function tn_Gb(a,b){this.expr=a;this.predicate=b}tn_Gb.prototype.evaluate=function(a){for(var b=this.expr.evaluate(a).c(),c=0;c<this.predicate.length;++c)for(var d=b,b=[],e=0;e<d.length;++e){var f=d[e];this.predicate[c].evaluate(a.clone(f,e,d)).d()&&b.push(f)}return new tn_p(b)};
function tn_Hb(a){this.expr=a}tn_Hb.prototype.evaluate=function(a){return new tn_o(-this.expr.evaluate(a).b())};function tn_Ib(a,b,c){this.expr1=a;this.expr2=c;this.op=b}
tn_Ib.prototype.evaluate=function(a){var b;switch(this.op.value){case "or":b=new tn_n(this.expr1.evaluate(a).d()||this.expr2.evaluate(a).d());break;case "and":b=new tn_n(this.expr1.evaluate(a).d()&&this.expr2.evaluate(a).d());break;case "+":b=new tn_o(this.expr1.evaluate(a).b()+this.expr2.evaluate(a).b());break;case "-":b=new tn_o(this.expr1.evaluate(a).b()-this.expr2.evaluate(a).b());break;case "*":b=new tn_o(this.expr1.evaluate(a).b()*this.expr2.evaluate(a).b());break;case "mod":b=new tn_o(this.expr1.evaluate(a).b()%
this.expr2.evaluate(a).b());break;case "div":b=new tn_o(this.expr1.evaluate(a).b()/this.expr2.evaluate(a).b());break;case "=":b=this.compare(a,function(a,b){return a==b});break;case "!=":b=this.compare(a,function(a,b){return a!=b});break;case "<":b=this.compare(a,function(a,b){return a<b});break;case "<=":b=this.compare(a,function(a,b){return a<=b});break;case ">":b=this.compare(a,function(a,b){return a>b});break;case ">=":b=this.compare(a,function(a,b){return a>=b});break;default:tn_g("BinaryExpr.evaluate: "+
this.op.value)}return b};
tn_Ib.prototype.compare=function(a,b){var c=this.expr1.evaluate(a),d=this.expr2.evaluate(a);if("node-set"==c.type&&"node-set"==d.type)for(var c=c.c(),e=d.c(),d=tn_b,f=0;f<c.length;++f)for(var h=0;h<e.length;++h)b(tn_h(c[f]),tn_h(e[h]))&&(d=tn_,h=e.length,f=c.length);else if("node-set"==c.type||"node-set"==d.type)if("number"==c.type){c=c.b();e=d.c();d=tn_b;for(f=0;f<e.length;++f)if(h=tn_h(e[f])-0,b(c,h)){d=tn_;break}}else if("number"==d.type){e=c.c();c=d.b();d=tn_b;for(f=0;f<e.length;++f)if(h=tn_h(e[f])-
0,b(h,c)){d=tn_;break}}else if("string"==c.type){c=c.a();e=d.c();d=tn_b;for(f=0;f<e.length;++f)if(h=tn_h(e[f]),b(c,h)){d=tn_;break}}else if("string"==d.type){e=c.c();c=d.a();d=tn_b;for(f=0;f<e.length;++f)if(h=tn_h(e[f]),b(h,c)){d=tn_;break}}else d=b(c.d(),d.d());else d="boolean"==c.type||"boolean"==d.type?b(c.d(),d.d()):"number"==c.type||"number"==d.type?b(c.b(),d.b()):b(c.a(),d.a());return new tn_n(!!d)};function tn_Jb(a){this.value=a}tn_Jb.prototype.evaluate=function(){return new tn_m(this.value)};
function tn_Kb(a){this.value=a}tn_Kb.prototype.evaluate=function(){return new tn_o(this.value)};function tn_Lb(a){this.name=a}tn_Lb.prototype.evaluate=function(a){return a.J(this.name)};function tn_t(a){return a}function tn_Mb(a,b){b.absolute=tn_;return b}function tn_Nb(a,b){b.absolute=tn_;b.ca(tn_u(a.value));return b}function tn_Ob(){var a=new tn_q;a.k(tn_u("."));a.absolute=tn_;return a}function tn_Pb(a){var b=new tn_q;b.absolute=tn_;b.k(tn_u(a.value));return b}
function tn_Qb(a){var b=new tn_q;b.k(a);return b}function tn_Rb(a,b,c){a.k(c);return a}function tn_Sb(a,b){a.k(tn_u(b.value));return a}function tn_Tb(a,b,c){b=new tn_q;b.rootExpr=a;b.k(c);return b}function tn_Ub(a){return tn_u(a.value)}function tn_Vb(a){return tn_u(a.value)}function tn_Wb(a,b,c){return new tn_r(a.value,c)}function tn_Xb(a,b){return new tn_r("attribute",b)}function tn_Yb(a){return new tn_r("child",a)}function tn_Zb(a,b){a.la(b);return a}
function tn_u(a){switch(a){case "//":return new tn_r("descendant-or-self",new tn_vb);case ".":return new tn_r("self",new tn_vb);case "..":return new tn_r("parent",new tn_vb)}}function tn__b(){return new tn_wb}function tn_0b(a){return new tn_Ab(a.value)}function tn_1b(a){return new tn_Bb(a.value)}function tn_2b(a){a=a.value.replace(/\s*\($/,"");switch(a){case "node":return new tn_vb;case "text":return new tn_xb;case "comment":return new tn_yb;case "processing-instruction":return new tn_zb("")}}
function tn_3b(a,b){var c=a.replace(/\s*\($/,"");"processing-instruction"!=c&&tn_g(c);return new tn_zb(b.value)}function tn_4b(a,b){return new tn_Cb(b)}function tn_5b(a,b){return b}function tn_6b(a){return new tn_Db(a)}function tn_7b(a,b,c,d){a=new tn_Db(a);a.T(c);for(c=0;c<d.length;++c)a.T(d[c]);return a}function tn_8b(a,b){return b}function tn_9b(a,b,c){return new tn_Eb(a,c)}function tn_$b(a,b,c){return new tn_Fb(a,c)}function tn_ac(a,b,c){c.ca(tn_u(b.value));return new tn_Fb(a,c)}
function tn_bc(a,b){return 0<b.length?new tn_Gb(a,b):a}function tn_cc(a,b){return new tn_Hb(b)}function tn_v(a,b,c){return new tn_Ib(a,b,c)}function tn_dc(a){a=a.value.substring(1,a.value.length-1);return new tn_Jb(a)}function tn_ec(a){return new tn_Kb(a.value)}function tn_fc(a,b){return new tn_Lb(b.value)}
function tn_8a(a){if("$"==a.charAt(0))return new tn_Lb(a.substr(1));if("@"==a.charAt(0)){a=new tn_Bb(a.substr(1));a=new tn_r("attribute",a);var b=new tn_q;b.k(a);return b}if(a.match(/^[0-9]+$/))return new tn_Kb(a);a=new tn_Bb(a);a=new tn_r("child",a);b=new tn_q;b.k(a);return b}function tn_9a(a){a=tn_Ca(a,"/");for(var b=new tn_q,c=0;c<a.length;++c){var d=new tn_Bb(a[c]),d=new tn_r("child",d);b.k(d)}return b}
var tn_s={ANCESTOR_OR_SELF:"ancestor-or-self",ANCESTOR:"ancestor",ATTRIBUTE:"attribute",CHILD:"child",DESCENDANT_OR_SELF:"descendant-or-self",DESCENDANT:"descendant",FOLLOWING_SIBLING:"following-sibling",FOLLOWING:"following",NAMESPACE:"namespace",PARENT:"parent",PRECEDING_SIBLING:"preceding-sibling",PRECEDING:"preceding",SELF:"self"},tn_gc=[tn_s.ANCESTOR_OR_SELF,tn_s.ANCESTOR,tn_s.ATTRIBUTE,tn_s.CHILD,tn_s.DESCENDANT_OR_SELF,tn_s.DESCENDANT,tn_s.FOLLOWING_SIBLING,tn_s.FOLLOWING,tn_s.NAMESPACE,tn_s.PARENT,
tn_s.PRECEDING_SIBLING,tn_s.PRECEDING,tn_s.SELF].join("|"),tn_hc={label:"|",prec:17,re:/^\|/},tn_fb={label:"//",prec:19,re:/^\/\//},tn_l={label:"/",prec:30,re:/^\//},tn_gb={label:"::",prec:20,re:/^::/},tn_ic={label:":",prec:1E3,re:/^:/},tn_jc={label:"[axis]",re:RegExp("^("+tn_gc+")")},tn_kc={label:"(",prec:34,re:/^\(/},tn_lc={label:")",re:/^\)/},tn_mc={label:"..",prec:34,re:/^\.\./},tn_nc={label:".",prec:34,re:/^\./},tn_eb={label:"@",prec:34,re:/^@/},tn_oc={label:",",re:/^,/},tn_db={label:"or",prec:10,
re:/^or\b/},tn_cb={label:"and",prec:11,re:/^and\b/},tn_pc={label:"=",prec:12,re:/^=/},tn_qc={label:"!=",prec:12,re:/^!=/},tn_rc={label:">=",prec:13,re:/^>=/},tn_sc={label:">",prec:13,re:/^>/},tn_tc={label:"<=",prec:13,re:/^<=/},tn_uc={label:"<",prec:13,re:/^</},tn_vc={label:"+",prec:14,re:/^\+/,left:tn_},tn_wc={label:"-",prec:14,re:/^\-/,left:tn_},tn_ab={label:"div",prec:15,re:/^div\b/,left:tn_},tn_bb={label:"mod",prec:15,re:/^mod\b/,left:tn_},tn_xc={label:"[",prec:32,re:/^\[/},tn_yc={label:"]",re:/^\]/},
tn_hb={label:"$",re:/^\$/},tn_zc={label:"[ncname]",re:RegExp("^"+tn_Ba)},tn_Ac={label:"*",prec:15,re:/^\*/,left:tn_},tn_Bc={label:"[litq]",prec:20,re:/^'[^\']*'/},tn_Cc={label:"[litqq]",prec:20,re:/^"[^\"]*"/},tn_Dc={label:"[number]",prec:35,re:/^\d+(\.\d*)?/},tn_ib={label:"[qname]",re:RegExp("^("+tn_Ba+":)?"+tn_Ba)},tn_Ec={label:"[nodetest-start]",re:/^(processing-instruction|comment|text|node)\(/},tn_$a=[tn_fb,tn_l,tn_mc,tn_nc,tn_gb,tn_ic,tn_jc,tn_Ec,tn_kc,tn_lc,tn_xc,tn_yc,tn_eb,tn_oc,tn_db,tn_cb,
tn_qc,tn_pc,tn_rc,tn_sc,tn_tc,tn_uc,tn_vc,tn_wc,tn_Ac,tn_hc,tn_bb,tn_ab,tn_Bc,tn_Cc,tn_Dc,tn_ib,tn_zc,tn_hb],tn_Fc={label:"LocationPath"},tn_w={label:"RelativeLocationPath"},tn_Gc={label:"AbsoluteLocationPath"},tn_x={label:"Step"},tn_y={label:"NodeTest"},tn_Hc={label:"Predicate"},tn_Ic={label:"Literal"},tn_z={label:"Expr"},tn_A={label:"PrimaryExpr"},tn_Jc={label:"Variablereference"},tn_Kc={label:"Number"},tn_Lc={label:"FunctionCall"},tn_Mc={label:"ArgumentRemainder"},tn_B={label:"PathExpr"},tn_Nc=
{label:"UnionExpr"},tn_Oc={label:"FilterExpr"},tn_Pc={label:"Digits"},tn_Qc=[tn_Fc,tn_w,tn_Gc,tn_x,tn_y,tn_Hc,tn_Ic,tn_z,tn_A,tn_Jc,tn_Kc,tn_Lc,tn_Mc,tn_B,tn_Nc,tn_Oc,tn_Pc],tn_qb={label:"?"},tn_pb={label:"*"},tn_rb={label:"+"},tn_Rc=[[tn_Fc,[tn_w],18,tn_t],[tn_Fc,[tn_Gc],18,tn_t],[tn_Gc,[tn_l,tn_w],18,tn_Mb],[tn_Gc,[tn_fb,tn_w],18,tn_Nb],[tn_Gc,[tn_l],0,tn_Ob],[tn_Gc,[tn_fb],0,tn_Pb],[tn_w,[tn_x],31,tn_Qb],[tn_w,[tn_w,tn_l,tn_x],31,tn_Rb],[tn_w,[tn_w,tn_fb,tn_x],31,tn_Sb],[tn_w,[tn_A,tn_l,tn_x],
31,tn_Tb],[tn_x,[tn_nc],33,tn_Ub],[tn_x,[tn_mc],33,tn_Vb],[tn_x,[tn_jc,tn_gb,tn_y],33,tn_Wb],[tn_x,[tn_eb,tn_y],33,tn_Xb],[tn_x,[tn_y],33,tn_Yb],[tn_x,[tn_x,tn_Hc],33,tn_Zb],[tn_y,[tn_Ac],33,tn__b],[tn_y,[tn_zc,tn_ic,tn_Ac],33,tn_0b],[tn_y,[tn_ib],33,tn_1b],[tn_y,[tn_Ec,tn_lc],33,tn_2b],[tn_y,[tn_Ec,tn_Ic,tn_lc],33,tn_3b],[tn_Hc,[tn_xc,tn_z,tn_yc],33,tn_4b],[tn_A,[tn_Jc],33,tn_t],[tn_A,[tn_kc,tn_z,tn_lc],33,tn_5b],[tn_A,[tn_Ic],30,tn_t],[tn_A,[tn_Kc],30,tn_t],[tn_A,[tn_Lc],30,tn_t],[tn_Lc,[tn_ib,
tn_kc,tn_lc],-1,tn_6b],[tn_Lc,[tn_ib,tn_kc,tn_z,tn_Mc,tn_pb,tn_lc],-1,tn_7b],[tn_Mc,[tn_oc,tn_z],-1,tn_8b],[tn_Nc,[tn_B],20,tn_t],[tn_Nc,[tn_Nc,tn_hc,tn_B],20,tn_9b],[tn_B,[tn_Fc],20,tn_t],[tn_B,[tn_Oc],19,tn_t],[tn_B,[tn_Oc,tn_l,tn_w],20,tn_$b],[tn_B,[tn_Oc,tn_fb,tn_w],20,tn_ac],[tn_Oc,[tn_A,tn_Hc,tn_pb],20,tn_bc],[tn_z,[tn_A],16,tn_t],[tn_z,[tn_Nc],16,tn_t],[tn_z,[tn_wc,tn_z],-1,tn_cc],[tn_z,[tn_z,tn_db,tn_z],-1,tn_v],[tn_z,[tn_z,tn_cb,tn_z],-1,tn_v],[tn_z,[tn_z,tn_pc,tn_z],-1,tn_v],[tn_z,[tn_z,
tn_qc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_uc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_tc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_sc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_rc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_vc,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_wc,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_Ac,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_ab,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_bb,tn_z],-1,tn_v,tn_],[tn_Ic,[tn_Bc],-1,tn_dc],[tn_Ic,[tn_Cc],-1,tn_dc],[tn_Kc,[tn_Dc],-1,tn_ec],[tn_Jc,[tn_hb,tn_ib],200,tn_fc]],tn_mb=[];
function tn_6a(){function a(a,b,c){a[b]||(a[b]=[]);a[b].push(c)}if(!tn_mb.length){tn_Rc.sort(function(a,b){var c=a[1].length,d=b[1].length;return c<d?1:c>d?-1:0});for(var b=1,c=0;c<tn_Qc.length;++c)tn_Qc[c].key=b++;for(c=0;c<tn_$a.length;++c)tn_$a[c].key=b++;for(c=0;c<tn_Rc.length;++c)for(var b=tn_Rc[c],d=b[1],e=d.length-1;0<=e;--e)if(d[e]==tn_rb){a(tn_mb,d[e-1].key,b);break}else if(d[e]==tn_pb||d[e]==tn_qb)a(tn_mb,d[e-1].key,b),--e;else{a(tn_mb,d[e].key,b);break}tn_Ga(tn_mb,function(){})}}
function tn_tb(a,b){for(var c=b.firstChild;c;c=c.nextSibling)a.push(c),arguments.callee(a,c)}function tn_ub(a,b){for(var c=b.lastChild;c;c=c.previousSibling)a.push(c),arguments.callee(a,c)}
function tn_5a(a,b){if(0!=b.length){for(var c=[],d=0;d<a.z();++d){for(var e=a.nodelist[d],f={node:e,key:[]},e=a.clone(e,0,[e]),h=0;h<b.length;++h){var j=b[h],m=j.expr.evaluate(e),k;"text"==j.type?k=m.a():"number"==j.type&&(k=m.b());f.key.push({value:k,order:j.order})}f.key.push({value:d,order:"ascending"});c.push(f)}c.sort(tn_Sc);f=[];for(d=0;d<c.length;++d)f.push(c[d].node);a.nodelist=f;a.Oa(0)}}
function tn_Sc(a,b){for(var c=0;c<a.key.length;++c){var d="descending"==a.key[c].order?-1:1;if(a.key[c].value>b.key[c].value)return 1*d;if(a.key[c].value<b.key[c].value)return-1*d}return 0}function tn_C(a,b){var c=tn_4a(a);return c=c.evaluate(b)};function tn_Tc(a,b){var c=(new tn_i).createDocumentFragment();tn_Uc(new tn_k(a,b),b,c);return c=tn_Ka(c)}
function tn_Uc(a,b,c){var d=9==c.nodeType?c:c.ownerDocument,e=b.nodeName.split(/:/);if(1==e.length||"xsl"!=e[0])tn_Vc(a,b,c,d);else switch(e[1]){case "apply-imports":alert("not implemented: "+e[1]);break;case "apply-templates":e=(e=tn_D(b,"select"))?tn_C(e,a).c():a.node.childNodes;a=a.clone(e[0],0,e);tn_Wc(a,b);tn_Xc(a,b);var f=tn_D(b,"mode"),d=b.ownerDocument.documentElement,e=[];for(b=0;b<d.childNodes.length;++b){var h=d.childNodes[b];1==h.nodeType&&("xsl:template"==h.nodeName&&h.getAttribute("mode")==
f)&&e.push(h)}for(d=0;d<a.z();++d){h=a.nodelist[d];for(b=0;b<e.length;++b)tn_Uc(a.clone(h,d),e[b],c)}break;case "attribute":e=tn_D(b,"name");e=tn_Yc(e,a);h=d.createDocumentFragment();tn_E(a,b,h);b=tn_h(h);c.setAttribute(e,b);break;case "attribute-set":alert("not implemented: "+e[1]);break;case "call-template":e=tn_D(b,"name");d=b.ownerDocument.documentElement;a=a.clone();tn_Wc(a,b);for(b=0;b<d.childNodes.length;++b)if(h=d.childNodes[b],1==h.nodeType&&"xsl:template"==h.nodeName&&h.getAttribute("name")==
e){tn_E(a,h,c);break}break;case "choose":tn_Zc(a,b,c);break;case "comment":h=d.createDocumentFragment();tn_E(a,b,h);b=tn_h(h);b=d.createComment(b);c.appendChild(b);break;case "copy":(h=tn__c(c,a.node,d))&&tn_E(a,b,h);break;case "copy-of":e=tn_D(b,"select");b=tn_C(e,a);if("node-set"==b.type){e=b.c();for(b=0;b<e.length;++b)tn_0c(c,e[b],d)}else h=tn_Qa(d,b.a()),c.appendChild(h);break;case "decimal-format":alert("not implemented: "+e[1]);break;case "element":e=tn_D(b,"name");e=tn_Yc(e,a);h=d.createElement(e);
c.appendChild(h);tn_E(a,b,h);break;case "fallback":alert("not implemented: "+e[1]);break;case "for-each":tn_1c(a,b,c);break;case "if":d=tn_D(b,"test");d=tn_C(d,a);d!=tn_a&&d.d()&&tn_E(a,b,c);break;case "import":alert("not implemented: "+e[1]);break;case "include":alert("not implemented: "+e[1]);break;case "key":alert("not implemented: "+e[1]);break;case "message":alert("not implemented: "+e[1]);break;case "namespace-alias":alert("not implemented: "+e[1]);break;case "number":alert("not implemented: "+
e[1]);break;case "otherwise":alert("error if here: "+e[1]);break;case "output":break;case "preserve-space":break;case "processing-instruction":alert("not implemented: "+e[1]);break;case "sort":break;case "strip-space":alert("not implemented: "+e[1]);break;case "stylesheet":case "transform":tn_E(a,b,c);break;case "template":(d=tn_D(b,"match"))&&tn_2c(d,a)&&tn_E(a,b,c);break;case "text":b=tn_h(b);h=d.createTextNode(b);c.appendChild(h);break;case "value-of":e=tn_D(b,"select");b=tn_C(e,a).a();h=d.createTextNode(b);
c.appendChild(h);break;case "param":tn_3c(a,b,tn_b);break;case "variable":tn_3c(a,b,tn_);break;case "when":alert("error if here: "+e[1]);break;case "with-param":alert("error if here: "+e[1]);break;default:alert("error if here: "+e[1])}}function tn_Wc(a,b){for(var c=0;c<b.childNodes.length;++c){var d=b.childNodes[c];1==d.nodeType&&"xsl:with-param"==d.nodeName&&tn_3c(a,d,tn_)}}
function tn_Xc(a,b){for(var c=[],d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(1==e.nodeType&&"xsl:sort"==e.nodeName){var f=tn_D(e,"select"),f=tn_4a(f),h=tn_D(e,"data-type")||"text",e=tn_D(e,"order")||"ascending";c.push({expr:f,type:h,order:e})}}tn_5a(a,c)}function tn_3c(a,b,c){var d=tn_D(b,"name"),e=tn_D(b,"select");0<b.childNodes.length?(e=b.ownerDocument.createDocumentFragment(),tn_E(a,b,e),b=new tn_p([e])):b=e?tn_C(e,a):new tn_m("");(c||!a.J(d))&&a.fa(d,b)}
function tn_Zc(a,b,c){for(var d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(1==e.nodeType)if("xsl:when"==e.nodeName){var f=tn_D(e,"test");if(tn_C(f,a).d()){tn_E(a,e,c);break}}else if("xsl:otherwise"==e.nodeName){tn_E(a,e,c);break}}}function tn_1c(a,b,c){var d=tn_D(b,"select"),d=tn_C(d,a).c();a=a.clone(d[0],0,d);tn_Xc(a,b);for(d=0;d<a.z();++d){var e=a.nodelist[d];tn_E(a.clone(e,d),b,c)}}function tn_E(a,b,c){a=a.clone();for(var d=0;d<b.childNodes.length;++d)tn_Uc(a,b.childNodes[d],c)}
function tn_Vc(a,b,c,d){if(3==b.nodeType)tn_4c(b)&&(d=d.createTextNode(b.nodeValue),c.appendChild(d));else if(1==b.nodeType){d=d.createElement(b.nodeName);for(var e=0;e<b.attributes.length;++e){var f=b.attributes[e];if(f){var h=f.nodeName,f=tn_Yc(f.nodeValue,a);d.setAttribute(h,f)}}c.appendChild(d);tn_E(a,b,d)}else tn_E(a,b,c)}
function tn_4c(a){if(!a.nodeValue.match(/^\s*$/))return tn_;a=a.parentNode;if("xsl:text"==a.nodeName)return tn_;for(;a&&1==a.nodeType;){var b=a.getAttribute("xml:space");if(b)if("default"==b)break;else if("preserve"==b)return tn_;a=a.parentNode}return tn_b}function tn_Yc(a,b){var c=tn_Ca(a,"{");if(1==c.length)return a;for(var d="",e=0;e<c.length;++e){var f=tn_Ca(c[e],"}");if(2!=f.length)d+=c[e];else var h=tn_C(f[0],b).a(),d=d+(h+f[1])}return d}
function tn_D(a,b){var c=a.getAttribute(b);return c?tn_Ra(c):c}function tn_0c(a,b,c){if(11==b.nodeType||9==b.nodeType)for(var d=0;d<b.childNodes.length;++d)arguments.callee(a,b.childNodes[d],c);else{var e=tn__c(a,b,c);if(e){for(d=0;d<b.attributes.length;++d)arguments.callee(e,b.attributes[d],c);for(d=0;d<b.childNodes.length;++d)arguments.callee(e,b.childNodes[d],c)}}}
function tn__c(a,b,c){if(1==b.nodeType)return b=c.createElement(b.nodeName),a.appendChild(b),b;3==b.nodeType?(b=c.createTextNode(b.nodeValue),a.appendChild(b)):4==b.nodeType?(b=c.createCDATASection(b.nodeValue),a.appendChild(b)):8==b.nodeType?(b=c.createComment(b.nodeValue),a.appendChild(b)):2==b.nodeType&&a.setAttribute(b.nodeName,b.nodeValue);return tn_a}
function tn_2c(a,b){var c=tn_4a(a),d;if(c.steps&&!c.absolute&&1==c.steps.length&&"child"==c.steps[0].axis&&0==c.steps[0].predicate.length)d=c.steps[0].nodetest.evaluate(b).d();else{d=tn_b;for(var e=b.node;!d&&e;){for(var f=c.evaluate(b.clone(e,0,[e])).c(),h=0;h<f.length;++h)if(f[h]==b.node){d=tn_;break}e=e.parentNode}}return d};function tn_5c(a,b){window[a]=b}tn_5c("nxslProcess",tn_Ya);tn_5c("xmlParse",tn_Wa);tn_5c("xsltProcess",tn_Tc);tn_5c("xmlText",tn_Ka);tn_5c("xmlImportNode",tn_Da);var tn_6c="http://www.gstatic.com/translate/infowindow/";function tn_7c(){return tn_6c+"transparent.png"}var tn_8c=Number.MAX_VALUE;var tn_9c="windo";function tn_F(a,b,c,d,e,f){var h=((b?b.ownerDocument:tn_a)||document).createElement(a);c&&tn_G(h,c);d&&tn_$c(h,d);h.style.display="none";b&&!e&&(tn_H(b,h),b[tn_9c]&&(h[tn_9c]=b[tn_9c]));f||window.setTimeout(function(){h.style.display=""},0);return h}function tn_ad(a,b){var c=((b?b.ownerDocument:tn_a)||document).createTextNode(a);b&&tn_H(b,c);return c}function tn_I(a){return tn_J(a)+"px"}function tn_G(a,b){var c=a.style;c.position="absolute";c.left=tn_I(b.x);c.top=tn_I(b.y)}
function tn_$c(a,b){var c=a.style;c.width=tn_I(b.width);c.height=tn_I(b.height)}function tn_K(a,b){a.style.width=tn_I(b)}function tn_L(a,b){a.style.height=tn_I(b)}function tn_M(a){a.style.display="none"}function tn_N(a){a.style.display=""}function tn_bd(a){a.style.visibility="hidden"}function tn_cd(a){a.style.visibility=""}function tn_dd(a){tn_ed(a,"hidden")}function tn_ed(a,b){a.style.overflow=b}var tn_O=Math.min,tn_P=Math.max,tn_J=Math.round;
function tn_Q(a,b){try{a.style.cursor=b}catch(c){"pointer"==b&&tn_Q(a,"hand")}}function tn_fd(a){tn_gd(a,"gmnoscreen");tn_hd(a,"gmnoprint")}function tn_id(a,b,c){return window.setTimeout(function(){b.apply(a)},c)}function tn_jd(a){a=a.target||a.srcElement;3==a.nodeType&&(a=a.parentNode);return a}function tn_H(a,b){a.appendChild(b)}function tn_R(a){a.parentNode&&(a.parentNode.removeChild(a),tn_kd(a))}function tn_ld(a){for(var b;b=a.firstChild;)tn_kd(b),a.removeChild(b)}
function tn_md(a,b){a.innerHTML!=b&&(tn_ld(a),a.innerHTML=b)}function tn_nd(a){tn_S.j()?a.style.MozUserSelect="none":(a.unselectable="on",a.onselectstart=tn_od)}function tn_pd(a,b){for(var c=a.length,d=0;d<c;++d)b(a[d],d)}function tn_qd(a,b,c){for(var d in a)(c||!a.hasOwnProperty||a.hasOwnProperty(d))&&b(d,a[d])}function tn_rd(a,b,c,d){c=c||0;for(d=d||b.length;c<d;++c)a.push(b[c])}function tn_od(){return tn_b}
function tn_sd(a,b){1==tn_S.type?a.style.filter="alpha(opacity="+tn_J(100*b)+")":a.style.opacity=b}function tn_td(a,b,c){a=tn_F("div",a,b,c);a.style.backgroundColor="black";tn_sd(a,0.35);return a}function tn_T(a,b){var c=(a?a.ownerDocument:tn_a)||document;if(a.currentStyle)return c=tn_ud(b),a.currentStyle[c];if(c.defaultView&&c.defaultView.getComputedStyle)return(c=c.defaultView.getComputedStyle(a,""))?c.getPropertyValue(b):"";c=tn_ud(b);return a.style[c]}var tn_vd="__mapsBaseCssDummy__";
function tn_wd(a,b,c){b=c?c:tn_T(a,b);if("number"==typeof b||isNaN(parseInt(b,10)))return b;if(2<b.length&&"px"==b.substring(b.length-2))return parseInt(b,10);(c=a.ownerDocument.getElementById(tn_vd))?a.parentNode.appendChild(c):(c=tn_F("div",a,new tn_c(0,0),new tn_U(0,0)),c.id=tn_vd,tn_bd(c));c.style.width="0px";c.style.width=b;return c.offsetWidth}var tn_xd="border-left-width",tn_yd="border-top-width";function tn_zd(a){return new tn_U(tn_Ad(a,tn_xd),tn_Ad(a,tn_yd))}
function tn_Ad(a,b){var c=tn_T(a,b);return isNaN(parseInt(c,10))?0:tn_wd(a,b,c)}function tn_ud(a){return a.replace(/-(\w)/g,function(a,c){return(""+c).toUpperCase()})}function tn_Bd(a){a.length=0}function tn_Cd(a){var b=tn_b;a&&"object"==typeof a&&(b="function"==typeof Window?a instanceof Window:"object"==typeof a.navigator&&"object"==typeof a.history&&"object"==typeof a.document);return b}function tn_Dd(a){return a=tn_Cd(a)?a:a&&a[tn_9c]?a[tn_9c]:window}
function tn_Ed(a,b){var c=tn_Dd(b);return a[tn_9c]=c};function tn_Fd(a,b,c){tn_Gd([a],function(a){b(a[0])},c)}
function tn_Gd(a,b,c){c=c||screen.width;var d=tn_F("div",window.document.body,new tn_c(-screen.width,-screen.height),new tn_U(c,screen.height)),e=[];for(c=0;c<a.length;c++){var f=tn_F("div",d,tn_c.ORIGIN);tn_H(f,a[c]);e.push(f)}window.setTimeout(function(){for(var c=[],f=new tn_U(0,0),m=0;m<e.length;m++){var k=e[m],g=new tn_U(k.offsetWidth,k.offsetHeight);c.push(g);k.removeChild(a[m]);tn_R(k);f.width=tn_P(f.width,g.width);f.height=tn_P(f.height,g.height)}tn_R(d);e=tn_a;b(c,f)},0)};function tn_Hd(a,b,c,d,e,f,h){e&&1==tn_S.type?(b=tn_F("div",b,c,d),b.style.overflow="hidden",d&&f&&(b.sizingMethod="scale"),d=tn_F("img",b),tn_bd(d),tn_Id(d,tn_Jd,tn_Kd)):(b=tn_F("img",b,c,d),h&&tn_Id(b,tn_Jd,tn_Ld));h&&(b.hideAndTrackLoading=tn_);tn_nd(b);1==tn_S.type&&(b.galleryImg="no");b.style.border=tn_I(0);b.style.padding=tn_I(0);b.style.margin=tn_I(0);b.oncontextmenu=tn_Md;tn_Nd(b,a);return b}
function tn_Kd(){var a=this.parentNode;a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod="+(a.sizingMethod?a.sizingMethod:"crop")+',src="'+this.src+'")';a.hideAndTrackLoading&&(a.loaded=tn_)}function tn_Nd(a,b){"DIV"==a.tagName?(a.firstChild.src=b,a.src=b,a.hideAndTrackLoading&&(a.style.filter="",a.loaded=tn_b)):a.hideAndTrackLoading&&b!=tn_7c()?(b!=tn_7c()?(a.loaded=tn_b,a.pendingSrc=b):a.pendingSrc=tn_a,a.src=tn_7c()):a.src=b}
function tn_Ld(){var a=this;a.src==tn_7c()&&a.pendingSrc?(a.src=a.pendingSrc,a.pendingSrc=tn_a):a.loaded=tn_};var tn_Od="click",tn_Pd="contextmenu",tn_Qd="dblclick",tn_Jd="load",tn_Rd="mousedown",tn_Sd="mousewheel",tn_Td="DOMMouseScroll",tn_Ud="unload",tn_Vd="closeclick",tn_Wd="maximizeclick",tn_Xd="restoreclick",tn_Yd="maximizeend",tn_Zd="restoreend",tn__d="clearlisteners",tn_0d="logclick";var tn_1d=tn_b;function tn_V(){this.n=[]}function tn_2d(){}tn_V.instance=function(a){a||(a=window);a.gEventListenerPool||(a.gEventListenerPool=new tn_V);return a.gEventListenerPool};tn_V.remove=function(a){tn_V.instance(tn_Dd(a)).Ia(a)};tn_V.prototype.Ia=function(a){var b=this.n.pop(),c=a.qa();c<this.n.length&&(this.n[c]=b,b.D(c));a.D(-1)};tn_V.push=function(a){tn_V.instance(tn_Dd(a)).Ha(a)};tn_V.prototype.Ha=function(a){this.n.push(a);a.D(this.n.length-1)};
tn_V.prototype.clear=function(){for(var a=0;a<this.n.length;++a)this.n[a].D(-1);this.n=[]};function tn_3d(a,b,c){a=new tn_W(a,b,c,0);tn_V.push(a);return a}function tn_4d(a){a.remove();tn_V.remove(a)}function tn_5d(a){tn_X(a,tn__d);tn_pd(tn_6d(a),function(a){a.remove();tn_V.remove(a)})}function tn_6d(a,b){var c=[],d=a.__e_;d&&(b?d[b]&&tn_rd(c,d[b]):tn_qd(d,function(a,b){tn_rd(c,b)}));return c}
function tn_7d(a,b,c){var d=tn_a,e=a.__e_;e?(d=e[b],d||(d=[],c&&(e[b]=d))):(d=[],c&&(a.__e_={},a.__e_[b]=d));return d}function tn_X(a,b,c){var d=[];tn_rd(d,arguments,2);tn_pd(tn_6d(a,b),function(b){if(tn_1d)b.apply(a,d);else try{b.apply(a,d)}catch(c){}})}
function tn_Id(a,b,c){3==tn_S.type&&b==tn_Qd?(a["on"+b]=c,c=new tn_W(a,b,c,3)):a.addEventListener?(a.addEventListener(b,c,tn_b),c=new tn_W(a,b,c,1)):a.attachEvent?(c=tn_8d(a,c),a.attachEvent("on"+b,c),c=new tn_W(a,b,c,2)):(a["on"+b]=c,c=new tn_W(a,b,c,3));var d=tn_Dd(a);(a!=d||b!=tn_Ud)&&tn_V.push(c);return c}function tn_Y(a,b,c,d){c=tn_9d(c,d);return tn_Id(a,b,c)}function tn_$d(a,b,c){tn_Y(a,tn_Od,b,c);1==tn_S.type&&tn_Y(a,tn_Qd,b,c)}
function tn_9d(a,b){return function(c){c||(c=window.event);c&&!c.target&&(c.target=c.srcElement);b.call(a,c,this)}}function tn_8d(a,b){return function(){return b.apply(a,arguments)}}function tn_W(a,b,c,d){tn_f(a);tn_f("function"==typeof c);var e=this;e.r=a;e.I=b;e.L=c;e.Xa=d;e.wa=-1;tn_Ed(e,a);tn_7d(a,b,tn_).push(e)}
tn_W.prototype.remove=function(){var a=this;switch(a.Xa){case 1:a.r.removeEventListener(a.I,a.L,tn_b);break;case 2:a.r.detachEvent("on"+a.I,a.L);break;case 3:a.r["on"+a.I]=tn_a}tn_Fa(tn_7d(a.r,a.I),a);a.r=tn_a;a.L=tn_a;a.remove=tn_2d;a.apply=tn_2d};tn_W.prototype.qa=function(){return this.wa};tn_W.prototype.D=function(a){this.wa=a};tn_W.prototype.apply=function(a,b){return this.L.apply(a,b)};function tn_kd(a){tn_Xa(a,tn_5d)}
function tn_ae(a){a.type==tn_Od&&tn_X(document,tn_0d,a);1==tn_S.type?(window.event.cancelBubble=tn_,window.event.returnValue=tn_b):(a.preventDefault(),a.stopPropagation())}function tn_be(a){a.type==tn_Od&&tn_X(document,tn_0d,a);1==tn_S.type?window.event.cancelBubble=tn_:a.stopPropagation()}function tn_Md(a){1==tn_S.type?window.event.returnValue=tn_b:a.preventDefault()};var tn_ce="opera msie chrome applewebkit firefox camino mozilla".split(" "),tn_de="x11; macintosh windows android ipad ipod iphone webos".split(" ");
function tn_Z(a){this.agent=a;this.os=this.type=-1;this.osVersion=0;this.cpu=-1;this.build=this.revision=this.version=0;a=a.toLowerCase();for(var b=0;b<tn_ce.length;b++){var c=tn_ce[b];if(-1!=a.indexOf(c)){this.type=b;b=RegExp(c+"[ /]?([0-9]+(.[0-9]+)?)");if(b=b.exec(a))this.version=parseFloat(b[1]);break}}if(6==this.type&&(b=/^Mozilla\/.*Gecko\/.*(Minefield|Shiretoko)[ /]?([0-9]+(.[0-9]+)?)/,b=b.exec(this.agent)))this.type=4,this.version=parseFloat(b[2]);if(3==this.type&&(b=/^.*Version\/?([0-9]+(.[0-9]+)?)/,
b=b.exec(this.agent)))this.build=this.version,this.version=parseFloat(b[1]);if(0==this.type&&(b=/^Opera\/9.[89].*Version\/?([0-9]+(.[0-9]+)?)/,b=b.exec(this.agent)))this.version=parseFloat(b[1]);for(b=0;b<tn_de.length;b++)if(c=tn_de[b],-1!=a.indexOf(c)){this.os=b;break}if(1==this.os){if(b=/Mac OS X[ ]+([0-9]+)[\._]([0-9]+)/,(b=b.exec(this.agent))&&3<=b.length)this.osVersion=parseFloat(b[1]+"."+b[2])}else if(2==this.os&&(b=/Windows NT ([0-9]+.[0-9]+)/,(b=b.exec(this.agent))&&2<=b.length))this.osVersion=
parseFloat(b[1]);1==this.os&&-1!=a.indexOf("intel")&&(this.cpu=0);b=/\brv:\s*(\d+\.\d+)/.exec(a);this.j()&&b&&(this.revision=parseFloat(b[1]));1==this.type&&(this.db=/win64;/.test(a))}tn_Z.bb="F9152AEC-3462-4632-8087-EEE3C3CDDA24";tn_Z.cb="application/geplugin";tn_Z.ab="getSelf";tn_Z.prototype.j=function(){return 4==this.type||6==this.type||5==this.type};tn_Z.OS_NAMES={};tn_Z.OS_NAMES[2]="windows";tn_Z.OS_NAMES[1]="macos";tn_Z.OS_NAMES[0]="unix";tn_Z.OS_NAMES[3]="android";tn_Z.OS_NAMES[6]="iphone";
tn_Z.OS_NAMES[-1]="other";tn_Z.BROWSER_NAMES={};tn_Z.BROWSER_NAMES[1]="ie";tn_Z.BROWSER_NAMES[4]="firefox";tn_Z.BROWSER_NAMES[2]="chrome";tn_Z.BROWSER_NAMES[3]="safari";tn_Z.BROWSER_NAMES[0]="opera";tn_Z.BROWSER_NAMES[5]="camino";tn_Z.BROWSER_NAMES[6]="mozilla";tn_Z.BROWSER_NAMES[-1]="other";var tn_S=new tn_Z(navigator.userAgent);tn_c.ORIGIN=new tn_c(0,0);tn_c.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function tn_U(a,b){this.width=a;this.height=b}tn_U.ZERO=new tn_U(0,0);tn_U.prototype.toString=function(){return"("+this.width+", "+this.height+")"};function tn_ee(a){this.minX=this.minY=tn_8c;this.maxX=this.maxY=-tn_8c;var b=arguments;if(a&&a.length)for(b=0;b<a.length;b++)this.extend(a[b]);else 4<=b.length&&(this.minX=b[0],this.minY=b[1],this.maxX=b[2],this.maxY=b[3])}
tn_ee.prototype.min=function(){return new tn_c(this.minX,this.minY)};tn_ee.prototype.max=function(){return new tn_c(this.maxX,this.maxY)};tn_ee.prototype.toString=function(){return"("+this.min()+", "+this.max()+")"};tn_ee.prototype.extend=function(a){var b=this;b.minX=tn_O(b.minX,a.x);b.maxX=tn_P(b.maxX,a.x);b.minY=tn_O(b.minY,a.y);b.maxY=tn_P(b.maxY,a.y)};
tn_ee.intersection=function(a,b){return new tn_ee([new tn_c(tn_P(a.minX,b.minX),tn_P(a.minY,b.minY)),new tn_c(tn_O(a.maxX,b.maxX),tn_O(a.maxY,b.maxY))])};function tn_hd(a,b){var c=a.className?""+a.className:"";if(c){for(var c=c.split(/\s+/),d=tn_b,e=0;e<c.length;++e)if(c[e]==b){d=tn_;break}d||c.push(b);a.className=c.join(" ")}else a.className=b}function tn_gd(a,b){var c=a.className?""+a.className:"";if(c&&-1!=c.indexOf(b)){for(var c=c.split(/\s+/),d=0;d<c.length;++d)c[d]==b&&c.splice(d--,1);a.className=c.join(" ")}};function tn_fe(){}tn_fe.monitor=function(){};tn_fe.monitorAll=function(){};tn_fe.dump=function(){};function tn__(){var a=tn_F("div",document.body),b=a.style;b.position="absolute";b.left=tn_I(7);b.bottom=tn_I(4);b.zIndex=1E4;var c=tn_td(a,new tn_c(2,2)),d=tn_F("div",a),b=d.style;b.position="relative";b.zIndex=1;b.fontFamily="Verdana,Arial,sans-serif";b.fontSize="small";b.border="1px solid black";var e=[["Clear",this.clear],["Close",this.close]],f=tn_F("div",d),b=f.style;b.position="relative";b.zIndex=2;b.backgroundColor="#979797";b.color="white";b.fontSize="85%";b.padding=tn_I(2);tn_Q(f,"default");
tn_nd(f);tn_ad("Log",f);for(b=0;b<e.length;b++){var h=e[b];tn_ad(" - ",f);var j=tn_F("span",f);j.style.textDecoration="underline";tn_ad(h[0],j);tn_$d(j,this,h[1]);tn_Q(j,"pointer")}d=tn_F("div",d);b=d.style;b.backgroundColor="white";b.width="80em";b.height="10em";b.overflow=tn_S.j()?"-moz-scrollbars-vertical":"auto";tn_Id(d,tn_Rd,tn_be);this.N=d;this.U=a;this.i=c}tn__.instance=function(){var a=tn__.r;a||(a=new tn__,tn__.r=a);return a};
tn__.prototype.write=function(a,b){var c=this.oa();b&&(c=tn_F("span",c),c.style.color=b);tn_ad(a,c);this.Ja()};tn__.prototype.clear=function(){this.N.innerHTML=""};tn__.prototype.close=function(){tn_R(this.U)};tn__.prototype.oa=function(){var a=tn_F("div",this.N),b=a.style;b.fontSize="85%";b.borderBottom="1px solid silver";b.paddingBottom=tn_I(2);b=tn_F("div",a);b.style.color="gray";b.style.fontSize="75%";tn_ad(this.Sa(),b);return a};
tn__.prototype.Ja=function(){this.N.scrollTop=this.N.scrollHeight;this.Qa()};tn__.prototype.Sa=function(){var a=new Date;return this.B(a.getHours(),2)+":"+this.B(a.getMinutes(),2)+":"+this.B(a.getSeconds(),2)+":"+this.B(a.getMilliseconds(),3)};tn__.prototype.B=function(a,b){for(var c=a.toString();c.length<b;)c="0"+c;return c};tn__.prototype.Qa=function(){tn_$c(this.i,new tn_U(this.U.offsetWidth,this.U.offsetHeight))};var tn_ge="overflow",tn_he="position",tn_ie="visible",tn_je="static",tn_ke="BODY";
function tn_le(a,b){for(var c=new tn_c(0,0);a&&a!=b;){a.nodeName==tn_ke&&tn_me(c,a);var d=tn_zd(a);c.x+=d.width;c.y+=d.height;if(a.nodeName!=tn_ke||!tn_S.j())c.x+=a.offsetLeft,c.y+=a.offsetTop;tn_S.j()&&(1.8<=tn_S.revision&&a.offsetParent&&a.offsetParent.nodeName!=tn_ke&&tn_T(a.offsetParent,tn_ge)!=tn_ie)&&(d=tn_zd(a.offsetParent),c.x+=d.width,c.y+=d.height);a.offsetParent&&(c.x-=a.offsetParent.scrollLeft,c.y-=a.offsetParent.scrollTop);if(1!=tn_S.type&&a.offsetParent&&(a.offsetParent.nodeName==tn_ke&&
tn_T(a.offsetParent,tn_he)==tn_je)&&(0==tn_S.type&&tn_T(a,tn_he)!=tn_je||0!=tn_S.type&&"absolute"==tn_T(a,tn_he))){tn_S.j()&&(c.x-=self.pageXOffset,c.y-=self.pageYOffset,d=tn_zd(a.offsetParent.parentNode),c.x+=d.width,c.y+=d.height);break}3==tn_S.type&&a.offsetParent&&(d=tn_zd(a.offsetParent),c.x-=d.width,c.y-=d.height);a=a.offsetParent}1==tn_S.type&&(!b&&document.documentElement)&&(c.x+=document.documentElement.clientLeft,c.y+=document.documentElement.clientTop);return b&&a==tn_a?(d=tn_le(b),new tn_c(c.x-
d.x,c.y-d.y)):c}
function tn_me(a,b){var c=tn_b;if(tn_S.j()){var c=tn_T(b,tn_ge)!=tn_ie&&tn_T(b.parentNode,tn_ge)!=tn_ie,d=tn_T(b,tn_he)!=tn_je;if(d||c){a.x+=tn_wd(b,"margin-left");a.y+=tn_wd(b,"margin-top");var e=tn_zd(b.parentNode);a.x+=e.width;a.y+=e.height}d&&(a.x+=tn_wd(b,"left"),a.y+=tn_wd(b,"top"))}if((tn_S.j()||1==tn_S.type)&&"BackCompat"!=document.compatMode||c)self.pageYOffset?(a.x-=self.pageXOffset,a.y-=self.pageYOffset):(a.x-=document.documentElement.scrollLeft,a.y-=document.documentElement.scrollTop)}
function tn_ne(a,b){if("undefined"!=typeof a.offsetX){var c=tn_jd(a),d=tn_le(c,b),e=new tn_c(a.offsetX,a.offsetY);3==tn_S.type&&(c=tn_zd(c),e.x-=c.width,e.y-=c.height);return new tn_c(d.x+e.x,d.y+e.y)}return"undefined"!=typeof a.clientX?(d=3==tn_S.type?new tn_c(a.pageX-self.pageXOffset,a.pageY-self.pageYOffset):new tn_c(a.clientX,a.clientY),e=tn_le(b),new tn_c(d.x-e.x,d.y-e.y)):tn_c.ORIGIN};function tn_oe(a){this.ticks=a;this.tick=0}tn_oe.prototype.reset=function(){this.tick=0};tn_oe.prototype.next=function(){this.tick++;var a=Math.PI*(this.tick/this.ticks-0.5);return(Math.sin(a)+1)/2};tn_oe.prototype.more=function(){return this.tick<this.ticks};tn_oe.prototype.extend=function(){this.tick>this.ticks/3&&(this.tick=tn_J(this.ticks/3))};var tn_pe=tn_b;function tn_qe(a,b,c){this.name=a;"string"==typeof b&&(a=tn_F("div",tn_a),tn_md(a,b),b=a);this.contentElem=b;b.style.zIndex=9500;this.onclick=c}function tn_0(){this.da=new tn_d(0,0,0,0);this.ba=tn_U.ZERO;this.f=[];this.l=[];this.Q=[];this.ha=[];this.s=this.v=0;this.q=this.H(tn_U.ZERO);this.g={};this.m=this.S=this.Aa=tn_b;this.ga=new tn_c(8,8);this.aa="ltr"}
tn_0.prototype.create=function(a,b){var c=this.g,d=tn_re(c,a,[["iw_n",628,6,0,0,"iw_n1"],["iw_n",628,6,0,0,"iw_n2"],["iw_w",6,598,0,0],["iw_e",6,598,0,0],["iw_s0",628,6,0,0,"iw_s1"],["iw_s0",628,6,0,0,"iw_s2"],["iw_c",628,598,0,0]]),e=new tn_U(6,6);tn_1(c,d,"iw_nw",e);tn_1(c,d,"iw_ne",e);tn_1(c,d,"iw_xtap",new tn_U(32,21));tn_1(c,d,"iw_xtap_l",new tn_U(32,21));tn_1(c,d,"iw_xtap_u",new tn_U(32,21));tn_1(c,d,"iw_xtap_ul",new tn_U(32,21));tn_1(c,d,"iw_xtap_rd",new tn_U(21,32));tn_1(c,d,"iw_xtap_ld",
new tn_U(21,32));tn_1(c,d,"iw_sw0",e,"iw_sw");tn_1(c,d,"iw_se0",e,"iw_se");tn_fd(d);this.e=d;var e=new tn_U(8,8),f=tn_re(c,b,[["iws_n",628,8,0,0,"iws_n1"],["iws_n",628,8,0,0,"iws_n2"],["iws_w",8,598,0,0],["iws_e",8,598,0,0],["iws_s",628,8,0,0,"iws_s1"],["iws_s",628,8,0,0,"iws_s2"],["iws_c",628,598,0,0]]);tn_1(c,f,"iws_nw",e);tn_1(c,f,"iws_ne",e);tn_1(c,f,"iws_sw",e);tn_1(c,f,"iws_se",e);tn_1(c,f,"iws_tap",new tn_U(37,16));tn_1(c,f,"iws_tap_l",new tn_U(32,16));tn_1(c,f,"iws_tap_u",new tn_U(37,26));
tn_1(c,f,"iws_tap_ul",new tn_U(32,26));tn_1(c,f,"iws_tap_rd",new tn_U(16,37));tn_1(c,f,"iws_tap_ld",new tn_U(26,37));tn_1(c,f,"iws_tab_dl",new tn_U(8,28));tn_1(c,f,"iws_tab_dr",new tn_U(14,28));tn_1(c,f,"iws_tab_l",new tn_U(8,28));tn_1(c,f,"iws_tab_r",new tn_U(14,28));tn_M(c.iws_tab_dl);tn_M(c.iws_tab_dr);tn_M(c.iws_tab_l);tn_M(c.iws_tab_r);tn_fd(f);this.i=f;e=new tn_U(14,13);f=tn_1(c,d,"close",e,"close",tn_);f.style.zIndex=1E4;tn_Q(f,"pointer");tn_$d(f,this,this.Fa);f=tn_1(c,d,"maximize",e,"maximize",
tn_);f.style.zIndex=1E4;tn_bd(f);tn_Q(f,"pointer");tn_$d(f,this,this.maximize);c=tn_1(c,d,"restore",e,"restore",tn_);c.style.zIndex=10001;tn_bd(c);tn_Q(c,"pointer");tn_$d(c,this,this.restore);tn_Y(d,tn_Rd,this,this.X);tn_Y(d,tn_Qd,this,this.pa);tn_Y(d,tn_Od,this,this.X);tn_Y(d,tn_Pd,this,tn_be);tn_Y(d,tn_Sd,this,tn_be);tn_Y(d,tn_Td,this,tn_be);this.Pa();this.hide()};tn_0.prototype.remove=function(){tn_R(this.i);tn_R(this.e)};
tn_0.prototype.ka=function(a){a?(tn_N(this.g.maximize),tn_N(this.g.restore)):(tn_M(this.g.maximize),tn_M(this.g.restore))};tn_0.prototype.G=function(a){this.g.close.style.visibility=a?"visible":"hidden"};tn_0.prototype.La=function(a){this.aa=a===tn_||"rtl"===a?"rtl":"ltr"};tn_0.prototype.za=function(a){this.Aa=a};tn_0.prototype.Ba=function(a){this.Ca=a};tn_0.prototype.ja=function(a){this.S=a};
tn_0.prototype.F=function(a){if(!a.getClientRects)return this.p(tn_ga(a));var b=this.A(),c=this.g,d=b.width,e=b.height,f=window.innerWidth||document.body.scrollWidth,b=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft,h=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_M(c.iw_xtap);tn_M(c.iw_xtap_l);tn_M(c.iw_xtap_u);tn_M(c.iw_xtap_ul);tn_M(c.iw_xtap_ld);tn_M(c.iw_xtap_rd);tn_M(c.iws_tap);tn_M(c.iws_tap_l);tn_M(c.iws_tap_u);tn_M(c.iws_tap_ul);
tn_M(c.iws_tap_ld);tn_M(c.iws_tap_rd);var j,m,k,g,c=a.getClientRects(),i=Array(c.length),n=tn_ga(a);a=c[0].top-n.y;for(var l=0;l<c.length;++l){i[l]={left:c[l].left,right:c[l].right,top:c[l].top,bottom:c[l].bottom};0<l&&i[l].bottom==i[l-1].bottom&&(i[l].left==i[l-1].right?(i[l].left=i[l-1].left,i[l].top=tn_O(i[l].top,i[l-1].top)):i[l].right==i[l-1].left&&(i[l].right=i[l-1].right,i[l].top=tn_O(i[l].top,i[l-1].top)));if(!j||i[l].left<=j.left)j=i[l];if(!m||i[l].right>=m.right)m=i[l];if(!k||i[l].top<=
k.top)k=i[l];if(!g||i[l].bottom>=g.bottom)g=i[l]}if(this.m&&21+d+6+12+m.right<f)return this.p(new tn_d(j.left+b,m.top-a,m.right-j.left,m.bottom-m.top));if(this.m&&18+d+21<j.left)return this.p(new tn_d(j.left+b,j.top-a,m.right-j.left,j.bottom-j.top));this.S&&21+e+6+12+(1<this.f.length?20:0)>n.y-(this.Ca?h:0)?(d=this.m,this.m=tn_b,k=this.p(new tn_d(g.left+b,k.top-a,g.right-g.left,g.bottom-k.top))):(d=this.m,this.m=tn_b,k=this.p(new tn_d(k.left+b,k.top-a,k.right-k.left,g.bottom-k.top)));this.m=d;return k};
tn_0.prototype.p=function(a,b){var c=this.A(),d=this.g,e=c.width,f=c.height,h=document.body.scrollWidth,j=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft,m=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_M(d.iw_xtap);tn_M(d.iw_xtap_l);tn_M(d.iw_xtap_u);tn_M(d.iw_xtap_ul);tn_M(d.iw_xtap_ld);tn_M(d.iw_xtap_rd);tn_M(d.iws_tap);tn_M(d.iws_tap_l);tn_M(d.iws_tap_u);tn_M(d.iws_tap_ul);tn_M(d.iws_tap_ld);tn_M(d.iws_tap_rd);var k=0,c=0,g,i,n,l,q,
p=0,s=this.m;s&&21+e+6+12+a.x+a.w<j+h?(i=tn_,f=d.iw_xtap_ld,m=d.iws_tap_ld):s&&18+e+21+j<a.x?(n=tn_,f=d.iw_xtap_rd,m=d.iws_tap_rd,c=5):(this.S&&21+f+6+12+(1<this.f.length?20:0)+(this.Ca?m:0)>a.y?(f=d.iw_xtap_u,m=d.iws_tap_u,k=0,g=tn_):(f=d.iw_xtap,m=d.iws_tap,k=0),tn_J(a.x+a.w/2)+32+6+12>j+h&&(f==d.iw_xtap_u?(f=d.iw_xtap_ul,m=d.iws_tap_ul):(f=d.iw_xtap_l,m=d.iws_tap_l),c=5,k=32),l=tn_J((e-32)/2),this.Aa&&(l+6+12+k+j>a.x+tn_J(a.w/2)?(l=a.x+tn_J(a.w/2)-6-12-k-j,0>l&&(p=tn_O(-l,tn_J(a.w/2)),l=0)):a.x+
tn_J(a.w/2)-k+e-l+18>j+h&&(g?(f=d.iw_xtap_ul,m=d.iws_tap_ul):(f=d.iw_xtap_l,m=d.iws_tap_l),c=5,k=32,l=a.x+tn_J(a.w/2)-k+e+6+12-h-j,l>e-32&&(p=tn_P(e-32-l,-tn_J(a.w/2)),l=e-32))),q=e-32-l);tn_N(f);tn_N(m);this.Wa=i?0:n?6+e+21:6+l+k;e=this.ba=b||tn_U.ZERO;p=this.Wa-p;d=i||n?6:g?0:this.ra().height+(1<this.f.length?20:0);p-=e.width;d-=e.height;this.fb=e=new tn_c(a.x+(i?a.w:n?0:a.w/2)-p,a.y+(i||n?a.h/2:g?a.h:0)-d);tn_G(this.e,e);tn_G(this.i,e);this.da=a;this.Ea=void 0;return this.Ga(i,n,g,l,q,f,m,c)};
tn_0.prototype.Ga=function(a,b,c,d,e,f,h,j){var m=!(a||b||c);this.R=f;this.P=h;var k=this.A(),g=this.g,i=k.width,n=k.height,l=1<this.f.length?this.v:0;c?(tn_K(g.iw_n1,tn_P(d,0)),tn_K(g.iw_n2,tn_P(e,0)),tn_K(g.iw_s1,i-l),tn_K(g.iw_s2,0),tn_K(g.iws_n1,tn_P(d,0)),tn_K(g.iws_n2,tn_P(e,0)),tn_K(g.iws_s1,i-l),tn_K(g.iws_s2,0)):m?(tn_K(g.iw_n1,i-l),tn_K(g.iw_n2,0),tn_K(g.iw_s1,tn_P(d,0)),tn_K(g.iw_s2,tn_P(e,0)),tn_K(g.iws_n1,i-l),tn_K(g.iws_n2,0),tn_K(g.iws_s1,tn_P(d,0)),tn_K(g.iws_s2,tn_P(e,0))):(tn_K(g.iw_n1,
i),tn_K(g.iw_n2,0),tn_K(g.iw_s1,i-l),tn_K(g.iw_s2,0),tn_K(g.iws_n1,i),tn_K(g.iws_n2,0),tn_K(g.iws_s1,i-l),tn_K(g.iws_s2,0));tn_$c(g.iw_c,k);a?(tn_L(g.iw_w,tn_P(n-32,0)),tn_L(g.iw_e,tn_P(n,32)),tn_L(g.iws_w,tn_P(n-32,0)),tn_L(g.iws_e,tn_P(n,32))):b?(tn_L(g.iw_e,tn_P(n-32,0)),tn_L(g.iw_w,tn_P(n,32)),tn_L(g.iws_e,tn_P(n-32,0)),tn_L(g.iws_w,tn_P(n,32))):(tn_L(g.iw_w,n),tn_L(g.iw_e,n),tn_L(g.iws_w,n),tn_L(g.iws_e,n));e=a?15:0;var k=e+5-2,q=e+6,p=q+5,s=q+i,y=s+5,r=a?0:b?s:q+d,C=r+j,B=r+32,D=B+5,i=c?15:
!a&&!b&&1<this.f.length?20:0,z=i+5-2,t=i+6,A=t+5,u=t+(a||b?tn_P(n,32):n),w=u+5,n=c||a||b?u:0;j=n+5-(c||a||b?0:2);d=c||a||b?u+6-1:0;var E=new tn_c(q,u),F=new tn_c(p,w),G=new tn_c(q,i),H=new tn_c(p,z);tn_G(g.iw_nw,new tn_c(e,i));tn_G(g.iws_nw,new tn_c(k,z));m?(tn_G(g.iw_n1,new tn_c(q+l,i)),tn_G(g.iws_n1,new tn_c(p+l,z)),tn_G(g.iw_s1,E),tn_G(g.iws_s1,F),tn_G(g.iw_s2,new tn_c(B,u)),tn_G(g.iws_s2,new tn_c(D,w)),tn_M(g.iws_tab_dl),tn_M(g.iws_tab_dr),tn_N(g.iws_tab_l),tn_N(g.iws_tab_r),tn_G(g.iws_tab_l,
new tn_c(k,j)),tn_G(g.iws_tab_r,new tn_c(p+l-14,j))):(tn_G(g.iw_n1,G),tn_G(g.iws_n1,H),tn_G(g.iw_s2,E),tn_G(g.iws_s2,F),tn_G(g.iw_s1,new tn_c(q+l,u)),tn_G(g.iws_s1,new tn_c(p+l,w)),tn_N(g.iws_tab_dl),tn_N(g.iws_tab_dr),tn_M(g.iws_tab_l),tn_M(g.iws_tab_r),tn_G(g.iws_tab_dl,new tn_c(k,j)),tn_G(g.iws_tab_dr,new tn_c(p+l-14,j)));c?(tn_G(g.iw_n2,new tn_c(B,i)),tn_G(g.iws_n2,new tn_c(D,z))):(tn_G(g.iw_n2,G),tn_G(g.iws_n2,H));tn_G(g.iw_ne,new tn_c(s,i));tn_G(g.iws_ne,new tn_c(y,z));tn_G(g.iw_w,new tn_c(e,
t+(a?32:0)));tn_G(g.iws_w,new tn_c(k,A+(a?32:0)));tn_G(g.iw_c,new tn_c(q,t));tn_G(g.iws_c,new tn_c(p,A));tn_K(g.iw_c,s-q);tn_L(g.iw_c,u-t);tn_K(g.iws_c,y-p);tn_L(g.iws_c,w-A);tn_G(g.iw_e,new tn_c(s,t+(b?32:0)));tn_G(g.iws_e,new tn_c(y,A+(b?32:0)));tn_G(g.iw_sw,new tn_c(e,u));tn_G(g.iws_sw,new tn_c(k,w));tn_G(g.iw_se,new tn_c(s,u));tn_G(g.iws_se,new tn_c(y,w));a?(tn_G(f,new tn_c(0,t)),tn_G(h,new tn_c(0,t))):b?(tn_G(f,new tn_c(s,t)),tn_G(h,new tn_c(y,t))):c?(tn_G(f,new tn_c(r,0)),tn_G(h,new tn_c(C,
0))):(tn_G(f,new tn_c(r,u)),tn_G(h,new tn_c(C,w)));a="rtl"==this.aa?-0+q:s-14+0;b=t-0;tn_G(g.close,new tn_c(a,b));"hidden"!=g.close.style.visibility&&(a="rtl"==this.aa?a+16:a-16);a=new tn_c(a,b);tn_G(g.maximize,a);tn_G(g.restore,a);this.ga=new tn_c(e+8,i+8);for(a=0;a<this.l.length;a++)b=this.l[a],tn_G(b,this.ga);if(2>this.f.length)tn_M(g.iws_tab_l),tn_M(g.iws_tab_r),tn_M(g.iws_tab_dl),tn_M(g.iws_tab_dr),tn_N(g.iw_sw),tn_N(g.iws_sw),tn_N(g.iw_nw),tn_N(g.iws_nw);else{m?(tn_M(g.iw_nw),tn_M(g.iws_nw),
tn_N(g.iw_sw),tn_N(g.iws_sw)):(tn_M(g.iw_sw),tn_M(g.iws_sw),tn_N(g.iw_nw),tn_N(g.iws_nw));for(a=0;a<this.f.length;++a){g=this.f[a];i=g.images;f=g.textWidth;b=g.labelNode;var p=b.style,v;0<a&&(v=this.ha[a-1]);tn_M(i.iw_tabback_dl);tn_M(i.iw_tabback_dm);tn_M(i.iw_tabback_dr);tn_M(i.iw_tabback_l);tn_M(i.iw_tabback_m);tn_M(i.iw_tabback_r);tn_M(i.iw_tab_dl);tn_M(i.iw_tab_dm);tn_M(i.iw_tab_dr);tn_M(i.iw_tab_l);tn_M(i.iw_tab_m);tn_M(i.iw_tab_r);tn_M(i.iws_tab_m);tn_M(i.iws_tab_dm);v?(tn_M(v.iws_tab_do),
tn_M(v.iws_tab_o)):(tn_M(i.iw_tab_1l),tn_M(i.iw_tab_1dl),tn_M(i.iw_tabback_1l),tn_M(i.iw_tabback_1dl),tn_M(i.iws_tab_1l),tn_M(i.iws_tab_1dl));var x;c=this.e.style.zIndex;m?(this.s==a?(h=0==a?i.iw_tab_1l:i.iw_tab_l,l=i.iw_tab_m,q=i.iw_tab_r,++c):(h=0==a?i.iw_tabback_1l:i.iw_tabback_l,l=i.iw_tabback_m,q=i.iw_tabback_r),i=i.iws_tab_m,v&&(x=v.iws_tab_o),p.paddingTop=tn_I(4),p.paddingBottom=tn_I(0)):(this.s==a?(h=0==a?i.iw_tab_1dl:i.iw_tab_dl,l=i.iw_tab_dm,q=i.iw_tab_dr,++c):(h=0==a?i.iw_tabback_1dl:i.iw_tabback_dl,
l=i.iw_tabback_dm,q=i.iw_tabback_dr),i=i.iws_tab_dm,v&&(x=v.iws_tab_do),p.paddingTop=tn_I(4),p.paddingBottom="");tn_N(h);tn_N(l);tn_N(q);tn_N(i);p=g.offset+(0==a?6:11);tn_G(h,new tn_c(e+g.offset,n));tn_G(l,new tn_c(e+p,n));tn_K(l,f);tn_G(i,new tn_c(k+2+p,j));tn_K(i,f);tn_G(q,new tn_c(e+p+f,n));x&&(tn_N(x),tn_G(x,new tn_c(k+p-14+2,j)),x.parentNode||tn_H(this.i,x));h.style.zIndex=c;l.style.zIndex=c;q.style.zIndex=c;f=f+2+3;tn_K(b,f);tn_G(b,new tn_c(e+p-2,d));tn_N(b);b.style.zIndex=c+1;!b.parentNode&&
0<g.textWidth&&tn_H(this.e,b)}}};tn_0.prototype.C=function(){this.Ea?this.F(this.Ea,this.ba):this.da&&this.p(this.da,this.ba)};tn_0.prototype.A=function(){return new tn_U(tn_P(this.q.width,this.v),this.q.height)};tn_0.prototype.reset=function(a,b,c,d,e){this.u(c,b,e);this.p(a,d);this.show();tn_bd(this.g.restore)};tn_0.prototype.hide=function(){this.R&&tn_M(this.R);this.P&&tn_M(this.P);tn_M(this.e);tn_M(this.i)};
tn_0.prototype.show=function(){this.ya()&&(tn_N(this.e),tn_N(this.i),this.R&&tn_N(this.R),this.P&&tn_N(this.P))};tn_0.prototype.Pa=function(){this.eb=tn_};tn_0.prototype.ya=function(){return"none"==this.e.style.display};tn_0.prototype.Ka=function(a){if(a!=this.s){this.ea(a);var b=this.l;tn_pd(b,tn_M);tn_N(b[a]);var c=this;window.setTimeout(function(){c.C()},0)}};tn_0.prototype.Fa=function(){tn_X(this,tn_Vd)};
tn_0.prototype.maximize=function(a){if(!this.M){tn_X(this,tn_Wd);tn_cd(this.g.restore);this.Ra=this.q;this.$a=this.f;this.Za=this.s;this.o=this.o||new tn_U(628,598);var b=new tn_U(4+this.o.width,4+this.o.height);tn_S.j()&&(b.width+=1);this.$(b,a)}};tn_0.prototype.Na=function(a){this.o=this.H(a)};tn_0.prototype.restore=function(a){this.M&&(tn_X(this,tn_Xd),tn_bd(this.g.restore),this.u(this.o,this.$a,this.Za),this.Ua=this.Ra,this.$(this.Ra,a))};
tn_0.prototype.$=function(a,b){this.Z=new tn_oe(b===tn_?1:10);this.K=this.q;this.ta=a;this.V()};tn_0.prototype.V=function(){var a=this.Z.next();this.Z.more()&&tn_id(this,this.V,10);var b=this.K.width+(this.ta.width-this.K.width)*a,a=this.K.height+(this.ta.height-this.K.height)*a;this.O(new tn_U(b,a));this.C();this.Ta();this.Z.more()||this.sa()};tn_0.prototype.sa=function(){this.M?(this.M=tn_b,tn_X(this,tn_Zd)):(this.M=tn_,tn_X(this,tn_Yd),this.o&&this.Da&&this.u(this.o,this.Da,this.Va))};
tn_0.prototype.O=function(a){return a=this.q=this.H(a)};tn_0.prototype.pa=function(a){if(1==tn_S.type)tn_ae(a);else{var b=tn_ne(a,this.e);b.y<=this.Y()&&tn_ae(a)}};tn_0.prototype.X=function(a){if(1==tn_S.type)tn_be(a);else{var b=tn_ne(a,this.e);b.y<=this.Y()&&(a.cancelDrag=tn_)}};tn_0.prototype.Y=function(){return this.A().height+12};tn_0.prototype.ra=function(){var a=this.A();return new tn_U(a.width+12,a.height+21+6)};
tn_0.prototype.u=function(a,b,c){this.na();this.Ua=a;a=new tn_U(4+a.width,4+a.height);tn_S.j()&&(a.width+=1);var d=this.O(a),e=[];this.f=e;var f=c||0;a=new tn_U(d.width+-4,d.height+-4);var h=this.ga,j=this.l=[];for(c=0;c<b.length;c++){var m=tn_F("div",this.e,h,a);tn_dd(m);c!=f&&tn_M(m);m.style.zIndex=10;tn_H(m,b[c].contentElem);j.push(m)}if(1<b.length){a=[];h=new tn_U(11,26);j=new tn_U(14,26);this.xa();for(c=0;c<b.length;++c){var k={images:b[c].images||{},textWidth:b[c].textWidth||0,offset:b[c].offset||
0,name:b[c].name,contentElem:b[c].contentElem,onclick:b[c].onclick},g=k.images;tn_re(g,this.e,[["iw_tabback_dm",1,26,0,0],["iw_tabback_m",1,26,0,0],["iw_tab_dm",1,26,0,0],["iw_tab_m",1,26,0,0]]);tn_1(g,this.e,"iw_tabback_dl",h);tn_1(g,this.e,"iw_tabback_dr",j);tn_1(g,this.e,"iw_tabback_l",h);tn_1(g,this.e,"iw_tabback_r",j);tn_1(g,this.e,"iw_tab_dl",h);tn_1(g,this.e,"iw_tab_dr",j);tn_1(g,this.e,"iw_tab_l",h);tn_1(g,this.e,"iw_tab_r",j);tn_re(g,this.i,[["iws_tab_dm",1,28,0,0],["iws_tab_m",1,28,0,0]]);
m=function(a,b){tn_M(b);a.Q.push(b)};if(0==c){var i=new tn_U(6,26);tn_1(g,this.e,"iw_tab_1dl",i);tn_1(g,this.e,"iw_tab_1l",i);tn_1(g,this.e,"iw_tabback_1dl",i);tn_1(g,this.e,"iw_tabback_1l",i);i=new tn_U(8,28);tn_1(g,this.i,"iws_tab_1dl",i);tn_1(g,this.i,"iws_tab_1l",i);m(this,g.iw_tab_1dl);m(this,g.iw_tab_1l);m(this,g.iw_tabback_1dl);m(this,g.iw_tabback_1l);m(this,g.iws_tab_1dl);m(this,g.iws_tab_1l)}m(this,g.iw_tabback_dl);m(this,g.iw_tabback_dm);m(this,g.iw_tabback_dr);m(this,g.iw_tabback_l);m(this,
g.iw_tabback_m);m(this,g.iw_tabback_r);m(this,g.iw_tab_dl);m(this,g.iw_tab_dm);m(this,g.iw_tab_dr);m(this,g.iw_tab_l);m(this,g.iw_tab_m);m(this,g.iw_tab_r);m(this,g.iws_tab_dm);m(this,g.iws_tab_m);g=document.createElement("div");k.labelNode=g;tn_L(g,20);i=g.style;tn_dd(g);i.fontWeight="bold";i.fontFamily="Arial,sans-serif";i.fontSize=tn_I(12);i.textAlign="center";i.display="inline";tn_se(g);tn_ad(k.name,g);(function(a,b,c,d){tn_$d(d,a,function(){a.Ka(b);c&&c()})})(this,c,b[c].onclick,g);this.Q.push(g);
a.push(g);this.f.push(k);0<c&&(k={},g=new tn_U(14,28),tn_1(k,this.i,"iws_tab_do",g),tn_1(k,this.i,"iws_tab_o",g),m(this,k.iws_tab_do),m(this,k.iws_tab_o),this.ha.push(k))}var n=this;tn_Gd(a,function(a){var b;if(a.length==e.length){for(var c=0;c<a.length;++c){var g=b=e[c];0!=a[c].width&&(g.textWidth=tn_P(0,a[c].width-2-3));tn_N(g.labelNode);tn_H(n.e,g.labelNode);if(0<c){var h=e[c-1];g.offset=h.offset+h.textWidth+(1==c?6:11)+14-11}}n.v=b.offset+b.textWidth+14+11-6;if(n.v+30>d.width){n.O(new tn_U(n.v+
30,d.height));a=new tn_U(n.v+30+-4,d.height+-4);for(c=0;c<n.l.length;++c)tn_$c(n.l[c],a)}}n.ea(f);n.C()})}else k={images:b[0].images||{},textWidth:b[0].textWidth||0,offset:b[0].offset||0,name:b[0].name,contentElem:b[0].contentElem,onclick:b[0].onclick},this.f.push(k),this.C()};tn_0.prototype.Ta=function(){for(var a=new tn_U(this.q.width+-4,this.q.height+-4),b=0;b<this.l.length;b++){var c=this.l[b];tn_$c(c,a)}};tn_0.prototype.Ma=function(a,b,c){this.o=a;this.Da=b;this.Va=c;tn_cd(this.g.maximize)};
tn_0.prototype.na=function(){var a=this.l;tn_pd(a,tn_R);tn_Bd(a);a=this.Q;tn_pd(a,tn_R);tn_Bd(a);this.s=0};tn_0.prototype.H=function(a){return new tn_U(tn_P(a.width,32),tn_P(a.height,0))};tn_0.prototype.xa=function(){this.Q=[];this.ha=[];this.v=0};tn_0.prototype.ea=function(a){tn_se(this.f[this.s].labelNode);this.s=a;tn_te(this.f[a].labelNode)};function tn_te(a){var b=a.style;b.color="";b.textDecoration="";tn_Q(a,"")}
function tn_se(a){var b=a.style;b.color="#0000cc";b.textDecoration="underline";tn_Q(a,"pointer")}function tn_re(a,b,c){b=tn_F("div",b,tn_a,tn_a,tn_b,tn_);for(var d=0;d<c.length;d++){var e=c[d],f=new tn_U(e[1],e[2]),h=new tn_c(e[3],e[4]),j=tn_6c+e[0]+".png",f=tn_Hd(j,b,h,f,tn_,tn_);a[e[5]||e[0]]=f}return b}
function tn_1(a,b,c,d,e,f){if(1==tn_S.type&&7>tn_S.version)return b=tn_Hd(tn_6c+c+(f?".gif":".png"),b,new tn_c(0,0),d,tn_,tn_),a[e||c]=b;tn_pe||(tn_pe=tn_,d=document.createElement("link"),d.rel="stylesheet",d.type="text/css",d.href=tn_6c+"iw_sprite.css",document.getElementsByTagName("head")[0].appendChild(d));d=document.createElement("div");d.className="SPRITE_"+c;d.style.overflow="hidden";b.appendChild(d);return a[e||c]=d};if(window.jstiming){window.jstiming.ma={};window.jstiming.Ya=1;var tn_ue=function(a,b,c){var d=a.t[b],e=a.t.start;if(d&&(e||c))return d=a.t[b][0],e=void 0!=c?c:e[0],d-e},tn_ve=function(a,b,c){var d="";window.jstiming.pt&&(d+="&srt="+window.jstiming.pt,delete window.jstiming.pt);try{window.external&&window.external.tran?d+="&tran="+window.external.tran:window.gtbExternal&&window.gtbExternal.tran?d+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(d+="&tran="+window.chrome.csi().tran)}catch(e){}var f=
window.chrome;if(f&&(f=f.loadTimes)){f().wasFetchedViaSpdy&&(d+="&p=s");if(f().wasNpnNegotiated){var d=d+"&npn=1",h=f().npnNegotiatedProtocol;h&&(d+="&npnv="+(encodeURIComponent||escape)(h))}f().wasAlternateProtocolAvailable&&(d+="&apa=1")}var j=a.t,m=j.start,f=[],h=[],k;for(k in j)if("start"!=k&&0!=k.indexOf("_")){var g=j[k][1];g?j[g]&&h.push(k+"."+tn_ue(a,k,j[g][0])):m&&f.push(k+"."+tn_ue(a,k))}delete j.start;if(b)for(var i in b)d+="&"+i+"="+b[i];(b=c)||(b="https:"==document.location.protocol?"https://csi.gstatic.com/csi":
"http://csi.gstatic.com/csi");return a=[b,"?v=3","&s="+(window.jstiming.sn||"translate")+"&action=",a.name,h.length?"&it="+h.join(","):"","",d,"&rt=",f.join(",")].join("")},tn_we=function(a,b,c){a=tn_ve(a,b,c);if(!a)return"";b=new Image;var d=window.jstiming.Ya++;window.jstiming.ma[d]=b;b.onload=b.onerror=function(){window.jstiming&&delete window.jstiming.ma[d]};b.src=a;b=tn_a;return a},tn_xe=function(a,b,c){if("prerender"==document.webkitVisibilityState)return tn_b;tn_we(a,b,c);return tn_};window.jstiming.report=
function(a,b,c){if("prerender"==document.webkitVisibilityState){var d="webkitvisibilitychange",e=tn_b,f=function(){e||(b?b.prerender="1":b={prerender:"1"},tn_xe(a,b,c)&&(e=tn_,document.removeEventListener(d,f,tn_b)))};document.addEventListener(d,f,tn_b);return""}return tn_we(a,b,c)}};var _infowindowVersion=1,_redirectUrl,tn_2,tn_3=tn_a,tn_4,tn_ye,tn_ze,tn_Ae=tn_b,tn_Be=tn_b,tn_5=tn_b,tn_6=tn_b,tn_Ce={right:"left",left:"right",ltr:"rtl",rtl:"ltr"},tn_De="/community",tn_Ee=tn_De+"/edit",tn_7,tn_Fe,tn_Ge,tn_He,tn_8,tn_Ie;function tn_Je(a){return a.substring(0,1).toUpperCase()+a.substring(1)}
var _intlStrings={_originalText:"Original Text:",_interfaceDirection:"ltr",_interfaceAlign:"left",_langpair:"",_currentBy:"",_unknown:"unknown",_suggestTranslation:"Suggest a translation",_submit:"Submit",_feedbackUrl:"http://translate.google.com/translate_suggestion",_suggestThanks:"Thank you for helping us improve the quality of our translations.",_reverse:tn_b};
function tn_Ke(a){if(3==a.nodeType)return a.nodeValue;if(1==a.nodeType){for(var b="",c=0;c<a.childNodes.length;++c)b+=tn_Ke(a.childNodes[c]);return b}return""}function tn_Le(a,b){if(a)if(3==b.nodeType)a.appendChild(document.createTextNode(b.nodeValue));else if(1==b.nodeType){var c;if("a"===b.nodeName||"A"===b.nodeName){c=document.createElement("a");var d=b.getAttribute("href");d&&c.setAttribute("href",d);a.appendChild(c)}else c=a;for(d=0;d<b.childNodes.length;++d)tn_Le(c,b.childNodes[d])}}
function tn_Me(){for(var a=document.getElementsByTagName("span"),b=0;b<a.length;++b){var c=a[b];if("google-tr-info"==c.className){var d=tn_Ne(c.firstChild.nodeValue,",",3);d&&"0"!==d[1]&&(c.parentNode.className="google-tr-highlight")}}}
function _setupIW(){if(!tn_Ae){tn_2=new tn_0;tn_4=document.createElement("div");tn_4.id="google-infowindow";tn_ye=document.createElement("span");tn_4.onmouseover=tn_Oe;tn_4.onmouseout=tn_Pe;document.body.appendChild(tn_ye);document.body.appendChild(tn_4);var a=document.createElement("div");document.body.appendChild(a);tn_M(a);a.innerHTML='<iframe id="google-feedback-frame" name="google-feedback-frame"></iframe>';tn_2.create(tn_4,tn_ye);tn_4.firstChild.style.zIndex=2147483647;tn_ye.firstChild.style.zIndex=
2147483647;tn_2.G(tn_);tn_2.za(tn_);tn_2.Ba(tn_);tn_2.ja(tn_);tn_2.ka(tn_b);tn_2.La(_intlStrings._interfaceDirection);tn_3d(tn_2,tn_Vd,function(){tn_Pe(tn_);tn_6&&tn_Qe(tn_b)});2==_infowindowVersion&&tn_Me();tn_Ae=tn_}}var tn_9=tn_a;function tn_Oe(){tn_Be=tn_;tn_Re(tn_3)}
function tn_Re(a){if(a&&(tn_9!==tn_a&&(window.clearTimeout(tn_9),tn_9=tn_a),!tn_5))if(tn_3==a)tn_6||(tn_ze=tn_3.style.backgroundColor,tn_3.style.backgroundColor="#E6ECF9");else{tn_6&&(tn_2.restore(tn_),tn_6=tn_b);for(var b,c=a.cloneNode(tn_),d=a.childNodes.length-1;0<=d;--d)"google-src-text"==a.childNodes[d].className?(b=a.childNodes[d].cloneNode(tn_),c.removeChild(c.childNodes[d]),b.className="google-src-active-text"):"google-tr-info"==a.childNodes[d].className&&c.removeChild(c.childNodes[d]);if(b){tn_2.G(tn_);
tn_ze=a.style.backgroundColor;a.style.backgroundColor="#E6ECF9";var e=document.createElement("div"),f=document.createElement("div"),h=document.createElement("img"),j=document.createElement("div");j.appendChild(h);h.width=48;h.height=17;h.border=0;h.style.display="inline";h.style.padding="0px";h.style.border="0px solid black";j.style.margin="0px";j.style.marginBottom="-17px";j.style.padding="0px";j.style.textAlign=tn_Ce[_intlStrings._interfaceAlign];h.src="http://www.google.com/images/logo_smallest.png";
h.style["margin"+tn_Je(_intlStrings._interfaceAlign)]="6px";h.style["margin"+tn_Je(tn_Ce[_intlStrings._interfaceAlign])]=tn_I(18);e.appendChild(j);e.appendChild(f);f.appendChild(document.createTextNode(_intlStrings._originalText));f.style.color="#333";f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;f.style.fontWeight="bold";f.style.fontSize="12px";f.style.minHeight="19px";f.style.fontFamily="arial,sans-serif";f.style["margin"+tn_Je(tn_Ce[_intlStrings._interfaceAlign])]=
tn_I(72);f=document.createElement("div");f.className="google-src-active-text";f.style.lineHeight="19px";f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;tn_Le(f,b);e.appendChild(f);e.style.zIndex=2147483647;if(0==_intlStrings._langpair.length)tn_3=a,tn_Fd(e,function(a){tn_2.hide();tn_2.u(a,[new tn_qe(_intlStrings._originalText,e)]);tn_2.F(tn_3);tn_2.show()},(document.width||document.body.scrollWidth)/2);else{var h=e.cloneNode(tn_),m=document.createElement("div");
m.appendChild(h);var k=document.createElement("div"),h=document.createElement("span"),f=document.createElement("div");f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;f.style.marginTop=tn_I(5);k.appendChild(f);j=document.createElement("img");j.src="http://www.google.com/images/zippy_plus_sm.gif";j.width=12;j.height=12;j.border=0;j.style.border="none";j.style.verticalAlign="middle";f.appendChild(j);f.appendChild(document.createTextNode(" "));f.appendChild(h);
h.appendChild(document.createTextNode(_intlStrings._suggestTranslation));h.style.direction=_intlStrings._interfaceDirection;h.style.textAlign=_intlStrings._interfaceAlign;h.style.color="#0000CC";h.style.textDecoration="underline";h.style.fontFamily="arial,sans-serif";h.style.fontSize="12px";f.onclick=tn_Se;tn_Q(h,"pointer");e.appendChild(k);var g=document.createElement("div"),h=document.createElement("div"),j=document.createElement("span");h.style.direction=_intlStrings._interfaceDirection;h.style.textAlign=
_intlStrings._interfaceAlign;h.style.marginTop=tn_I(5);h.style.marginBottom=tn_I(6);g.appendChild(h);var i=document.createElement("img");i.src="http://www.google.com/images/zippy_minus_sm.gif";i.width=12;i.height=12;i.border=0;i.style.border="none";i.style.verticalAlign="middle";h.appendChild(i);h.appendChild(document.createTextNode(" "));h.appendChild(j);j.appendChild(document.createTextNode(_intlStrings._suggestTranslation));j.style.direction=_intlStrings._interfaceDirection;j.style.textAlign=_intlStrings._interfaceAlign;
j.style.color="#0000CC";j.style.textDecoration="underline";j.style.fontFamily="arial,sans-serif";j.style.fontSize="12px";h.onclick=function(){tn_Qe(tn_)};tn_Q(j,"pointer");tn_3=a;if(1==_infowindowVersion){var n=document.createElement("div"),f=document.createElement("form");f.style.marginBottom="0px";f.style.paddingBottom="0px";f.target="google-feedback-frame";f.method="post";f.action=_intlStrings._feedbackUrl;n.appendChild(f);var l=document.createElement("input");l.type="hidden";l.name="gtrans";f.appendChild(l);
_intlStrings._reverse?(a=tn_Ke(c),c=tn_Ke(b)):(c=tn_Ke(c),a=tn_Ke(b));l.value=c;b=document.createElement("input");b.type="hidden";b.value=a;b.name="text";f.appendChild(b);b=document.createElement("input");b.name="langpair";b.type="hidden";b.value=_intlStrings._langpair;f.appendChild(b);b=document.createElement("input");b.name="u";b.type="hidden";b.value=tn_$("u");f.appendChild(b);b=document.createElement("input");b.name="oe";b.type="hidden";if(document.charset)b.value=document.charset,f.appendChild(b);
else if(document.characterSet)b.value=document.characterSet,f.appendChild(b);else if(a=tn_$("oe"))f.appendChild(b),b.value=a;var q=document.createElement("textarea");q.rows=3;q.name="utrans";q.value=c;f.appendChild(q);b=document.createElement("div");b.style.direction=_intlStrings._interfaceDirection;b.style.textAlign=tn_Ce[_intlStrings._interfaceAlign];b.style.marginTop=tn_I(6);b.style.marginBottom="0px";f.appendChild(b);c=document.createElement("input");c.type="submit";c.value=_intlStrings._submit;
b.appendChild(c);var p=document.createElement("div");p.appendChild(document.createElement("hr"));p.appendChild(document.createTextNode(_intlStrings._suggestThanks));p.style.direction=_intlStrings._interfaceDirection;p.style.textAlign=_intlStrings._interfaceAlign;p.style.fontFamily="arial,sans-serif";p.style.fontSize="12px";p.style.overflow="auto";p.style.marginTop="10px";tn_M(p);g.appendChild(n);m.appendChild(g);m.appendChild(p);f.onsubmit=function(){window.setTimeout(function(){tn_M(g);tn_N(p)},
1);tn_5=tn_b;return q.value!=l.value};tn_Gd([m,e],function(a){q.style.width=tn_I(a[0].width-6);q.style.padding=tn_I(2);tn_2.hide();tn_2.u(a[1],[new tn_qe(_intlStrings._originalText,e)]);tn_2.Ma(a[0],[new tn_qe(_intlStrings._originalText,m)]);tn_2.F(tn_3);tn_2.G(tn_);tn_2.show()},(document.width||document.body.scrollWidth)/2)}else if(2==_infowindowVersion){(j=tn_$("rurl"))||(j="translate.google.com");h=_intlStrings._langpair.split("|",2);i="hl="+tn_$("hl")+"&sl="+h[0]+"&tl="+h[1];try{tn_7=document.createElement('<iframe name="google-edit-frame">')}catch(s){tn_7=
document.createElement("iframe")}tn_7.id="google-edit-frame";tn_7.name="google-edit-frame";tn_7.style.margin=0;tn_7.style.padding=0;tn_7.frameBorder=0;tn_7.width=650;tn_7.height=350;e.appendChild(tn_7);h=e.cloneNode(tn_);for(d=0;d<a.childNodes.length;++d)if("google-tr-info"==a.childNodes[d].className){n=a.childNodes[d].firstChild.nodeValue;break}n?(a=tn_Ne(n,",",3))&&"0"!==a[1]?(tn_7.src="http://translate.google.com"+tn_De+"/authorinfo?"+i+"&uid="+a[0]+"&date="+a[1],tn_7.height=15):tn_7.style.display=
"none":tn_7.style.display="none";if(!tn_Fe){try{tn_Fe=document.createElement('<iframe name="google-send-frame">')}catch(y){tn_Fe=document.createElement("iframe")}tn_Fe.name="google-send-frame";window.document.body.appendChild(tn_Fe);tn_Fe.style.display="none";a="http://"+j+tn_De+"/send?domain="+window.location.host;(d=tn_$("hl"))&&(a+="&hl="+d);tn_Fe.src=a}var r=document.createElement("form");r.style.display="none";r.target="google-edit-frame";r.method="post";a="http://"+j+tn_Ee+"?"+i;j=new Date;
a+="&ctz="+j.getTimezoneOffset();e.appendChild(r);i=document.createElement("input");i.name="sentence";i.type="hidden";i.value=_intlStrings._reverse?c.innerHTML:b.innerHTML;if(j=document.documentMode)i.value=encodeURIComponent(i.value),a+="&escape=1";r.appendChild(i);r.action=a;!n&&!tn_$("mt")&&(n=document.createElement("input"),n.type="hidden",n.name="showtrans",n.value=_intlStrings._reverse?b.innerHTML:c.innerHTML,j&&(n.value=encodeURIComponent(n.value)),r.appendChild(n));b=document.createElement("input");
b.name="u";b.type="hidden";b.value=tn_$("u");r.appendChild(b);b=document.createElement("input");b.name="domain";b.type="hidden";b.value=window.location.host;r.appendChild(b);f.onclick=function(){_redirectUrl?0<_redirectUrl.indexOf("/community/login?")?window.open(_redirectUrl):window.top.location=_redirectUrl:(r.submit(),k.parentNode.replaceChild(g,k),tn_Se())};tn_Ge=k;tn_He=g;tn_Gd([h,e],function(a){tn_2.hide();tn_2.u(a[1],[new tn_qe(_intlStrings._originalText,e)]);tn_2.Na(a[0]);tn_2.F(tn_3);tn_2.G(tn_);
tn_2.show()},650)}}}}}function tn_$(a){for(var b=window.location.search.substring(1),b=b.split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0].toLowerCase()==a&&0<d.length)return window.unescape(d[1])}return""}function tn_Te(a){tn_Ae&&(tn_Be=tn_,tn_5||(tn_9!==tn_a&&(window.clearTimeout(tn_9),tn_9=tn_a),tn_3==a?(tn_ze=tn_3.style.backgroundColor,tn_3.style.backgroundColor="#E6ECF9"):tn_9=window.setTimeout(function(){tn_Re(a)},500)))}
function tn_Pe(a){tn_Ae&&(a!==tn_&&(tn_Be=tn_b),tn_5||(tn_3&&tn_3.style&&(tn_3.style.backgroundColor=tn_ze),tn_9&&(window.clearTimeout(tn_9),tn_9=tn_a),a!==tn_?tn_9=window.setTimeout(tn_Ue,250):tn_Ue()))}function tn_Ue(){tn_5||(tn_2.hide(),tn_6&&(tn_2.restore(tn_),tn_6=tn_b),tn_3=tn_a)}function tn_Se(){tn_6=tn_5=tn_;var a=tn_3d(tn_2,tn_Yd,function(){2==_infowindowVersion&&(tn_7.height=350,tn_7.style.display="block");tn_4d(a)});tn_2.maximize()}
function tn_Qe(a){2==_infowindowVersion&&tn_He.parentNode.replaceChild(tn_Ge,tn_He);var b=tn_3d(tn_2,tn_Zd,function(){tn_4d(b);tn_6=tn_b;a?window.setTimeout(function(){tn_5=tn_b;tn_Be||tn_Pe(tn_)},500):(tn_5=tn_b,tn_Be||tn_Pe(tn_))});tn_2.restore()}function _csi(a,b){var c={};c.sl=a;c.tl=b;var d=window.jstiming.load;d.tick("prt");d.tick("ol");d.name="w";window.jstiming.sn="translate";window.jstiming.report(d,c);try{window.external&&window.external.resT()}catch(e){}}
function tn_Ne(a,b,c){if(!a)return tn_a;for(var d=[],e=0,f=0;f<c-1;++f){var h=a.indexOf(b,e);if(-1==h)return tn_a;d[f]=a.substring(e,h);e=h+b.length}d[c-1]=a.substring(e);return d}
function tn_Ve(a){if("reload"==a)window.location.reload();else if("restore"==a){if(tn_8&&tn_Ie){for(tn_8.style.backgroundColor=tn_Ie.style.backgroundColor;tn_8.hasChildNodes();)tn_8.removeChild(tn_8.firstChild);for(;tn_Ie.hasChildNodes();)tn_8.appendChild(tn_Ie.firstChild);tn_8=tn_a}}else if(tn_3){tn_3.style.backgroundColor=tn_ze;if((a=tn_Ne(a,"|",3))&&!tn_$("mt")){tn_8=tn_3;tn_Ie=tn_3.cloneNode(tn_);for(var b=tn_3.childNodes.length-1;0<=b;--b){var c=tn_3.childNodes[b];"google-src-text"!=c.className&&
tn_3.removeChild(c)}b=document.createElement("span");b.className="google-tr-info";b.appendChild(document.createTextNode(a[0]+","+(new Date).getTime()+","+a[1]));tn_3.appendChild(b);c=document.createElement("div");c.innerHTML=a[2];for(b=0;b<c.childNodes.length;++b)tn_3.appendChild(c.childNodes[b].cloneNode(tn_))}tn_5=tn_b;tn_Ue();tn_Me()}}function tn_We(a){var b=window.onload;window.onload=b?function(){try{a()}catch(c){}b()}:a}var _tipon=tn_Te,_tipoff=tn_Pe,_updatec=tn_Ve,_addload=tn_We,tn_Xe=window.jstiming.load;
tn_Xe.tick("jl");
