String.prototype.format=function(){for(var f=this,c=0;c<arguments.length;c++)f=f.replace(RegExp("\\{"+c+"\\}","gi"),arguments[c]);return f};
var CSSRules=function(){var f=document.getElementsByTagName("head")[0],c=document.createElement("style");c.type="text/css";f.appendChild(c);return{add:function(){return c.styleSheet?function(f,g){if(c.styleSheet.cssText=="")c.styleSheet.cssText="";c.styleSheet.cssText+=f+" { "+g+" }"}:function(f,g){c.appendChild(document.createTextNode(f+" { "+g+" }"))}}()}}(),_gaq=_gaq||[],TT_Analytics=function(){var f=typeof _gaq!="undefined"||typeof _gat!="undefined"||typeof pageTracker!="undefined"?"tt.":"",c=
Math.random()*2E3<1;_gaq.push([f+"_setAccount","UA-29174715-3"]);return{log:function(n,g,h){if(c){try{h&&(h=Math.round(h))}catch(p){h=0}g!=null&&h!=null?_gaq.push([f+"_trackEvent","Tumblr",n,g,h]):g!=null?_gaq.push([f+"_trackEvent","Tumblr",n,g]):_gaq.push([f+"_trackEvent","Tumblr",n])}}}}(),TopicTorch=function(){function f(){var a=navigator.appName=="Microsoft Internet Explorer"&&document.compatMode=="BackCompat";f=function(){return a};return f()}function c(){b=jQuery.noConflict(!0);n();if(typeof preloadedRelatedTermsData!=
"undefined")t(preloadedRelatedTermsData);else if(!u)try{u=!0;var a=encodeURIComponent(window.location.href),d=encodeURIComponent(document.referrer),e=escape(navigator.userAgent),f=TopicTorch.getClientIP,o="seh"+TopicTorch.getInstallId.replace(/-/g,"").substr(0,27),k="&params=segment%3Did"+TopicTorch.bid.toString().substr(2),d="http://topictorch.netseer.com/dsatserving2/servlet/BannerServer?rt=jsonp,TopicTorch.process&impt=11&imps=23&tlid="+tlid+"&url="+a+"&referral_page="+d+"&ua="+e+"&ip="+f+"&evid="+
o+k;TT_Analytics.log("page",a);var c=document.createElement("script");c.type="text/javascript";c.src=d;document.getElementsByTagName("head")[0].appendChild(c)}catch(g){}}function n(){CSSRules.add("#TT_Frame","display:none;position:fixed;_position:absolute; top:auto; right:auto; bottom:0px;  _bottom:expression(eval(closed ? 40 : 0 - document.body.scrollTop));left:0px;font-size:15px !important;font-family: Arial, sans-serif !important;text-shadow:none; margin:0; ");CSSRules.add("#TT_Frame","z-index:"+
(l.zIndex?l.zIndex.toString():"2147483647"));CSSRules.add("#TT_Frame.side","position:fixed;top:0px; bottom:auto; _position:absolute;_bottom:auto; _top:eval(document.body.scrollTop);");CSSRules.add("#TT_Frame.side.left","left:0px; right:auto;");CSSRules.add("#TT_Frame.side.right","left:auto; right:0px;");CSSRules.add("#TT_Frame","width:100%; height:34px;");CSSRules.add("#TT_Frame.small","font-size:12px !important;");CSSRules.add("#TT_Frame.side","width:160px; height:100%;");CSSRules.add("#TT_Bg","width: 100%; height:100%;background: none repeat scroll 0% 0% rgb(250, 250, 250); border: medium none rgb(250, 250, 250); padding: 0px; margin: 0px; border-radius: 0px 0px 2px 2px; box-shadow: 0px 0px 5px rgb(0, 0, 0); display: block;");
CSSRules.add("#TT_Close_Btn","position:absolute; top:12px; right:3px; bottom:auto; left:auto; width: 10px; height: 10px; background:url(http://api.topictorch.com/app/img/tt_buttons.png) no-repeat -1px -32px; cursor:pointer");CSSRules.add(".side #TT_Close_Btn","top:5px;right:5px;");CSSRules.add("#TT_Close_Btn.hover","background-position:-1px -32px;");CSSRules.add("#TT_Search_Bg","position:absolute; top:4px; right:15px; bottom:auto; left:auto; width:245px; height:25px; z-index:9999999999; background:url(http://api.topictorch.com/app/img/tt_buttons.png) no-repeat -2px -3px;");
CSSRules.add(".small #TT_Search_Bg","width:200px");CSSRules.add(".side #TT_Search_Bg","top:25px;right:auto;bottom:auto;left:0; width:160px !important;");CSSRules.add("#TT_Search_Btn","position:absolute; top:1px; right:0px; bottom:auto;left:auto; width:50px; height:25px; cursor:pointer; background:url(http://api.topictorch.com/app/img/tt_buttons.png) no-repeat -249px -4px;");CSSRules.add("#TT_Search_Btn.hover","background-position:-298px -4px;");CSSRules.add("#TT_Search_Btn.click","background-position:-347px -4px");
CSSRules.add("#TT_Search_Txt","position:absolute;top:-2px;right:auto;bottom:auto;left:5px; background-color:transparent !important; background:none; border:0; color:#808080; width:190px; height:100%;outline:none; margin:0; padding:2px");CSSRules.add(".small #TT_Search_Txt","width:145px;");CSSRules.add(".side #TT_Search_Txt","width:120px; !important");CSSRules.add("#TT_Branding","position:absolute; top:8px; right:auto; bottom:auto; left:15px; width:16px; height:16px; background:url(http://api.topictorch.com/app/img/tt_buttons.png) no-repeat -20px -31px; cursor:pointer;");
CSSRules.add(".side #TT_Branding","top:2px; left:2px;");CSSRules.add("#TT_Branding.hover","background-position:-46px -31px;");CSSRules.add("#TT_Related","position:absolute; overflow:hidden;");CSSRules.add("#TT_Related","top:4px; right:auto; bottom:auto; left:45px;height:22px; ");CSSRules.add(".side #TT_Related","top:65px; right:auto;bottom:auto; left:0; height:auto;");CSSRules.add("#TT_Related ul","line-height: 24px; margin:0; padding:0; list-style: none; text-align:left;");CSSRules.add("#TT_Related ul li",
"background:none;background-image:none !important;float:left; margin:0 7px;list-style:none;color:#000; background:none; padding:0;list-style: none; line-height:24px !important;");CSSRules.add(".small #TT_Related ul li","background:none;background-image:none !important;margin:0 0 0 5px;list-style: none;");CSSRules.add(".side #TT_Related ul li","float:none; display:block; margin-bottom:20px;");CSSRules.add(".side #TT_Related ul li:first-child","margin-bottom:5px;");CSSRules.add(".side #TT_Related ul li.divider",
"display:none;");CSSRules.add("#TT_Related ul li:last","background:none;background-image !important:none;margin:0; padding:0;list-style: none;");CSSRules.add("#TT_Related a","color:#0645AD !important; text-decoration:none; text-shadow:none; font-weight:600; padding:0; margin:0;");CSSRules.add(".side #TT_Related a","display:block; line-height:20px;");CSSRules.add("#TT_Related a:hover","color:#0645AD; text-decoration:underline;padding:0; margin:0;");var a=document.createElement("div");a.id="TT_Frame";
if(m)switch(b(a).addClass("side"),m){case i.LEFT:b(a).addClass("left");break;case i.RIGHT:b(a).addClass("right")}h();var d=document.createElement("div");d.id="TT_Bg";var e=document.createElement("div");e.id="TT_Close_Btn";b(e).mouseenter(function(){b(this).addClass("hover")}).mouseleave(function(){b(this).removeClass("hover")}).click(function(){var a=b("#TT_Frame"),d={};a.hasClass("left")?d.left=-175:a.hasClass("right")?d.right=-175:d.bottom=f()?-(b(window).scrollTop()+40):-40;a.stop().animate(d);
h(!0);B()});var c=document.createElement("div");c.id="TT_Search_Bg";var o=document.createElement("div");o.id="TT_Search_Btn";b(o).mouseenter(function(){b(this).addClass("hover")}).mouseleave(function(){b(this).removeClass("hover")}).mousedown(function(){b(this).addClass("click")}).mouseup(function(){b(this).removeClass("click")}).click(function(){v()});var k=document.createElement("input");k.id="TT_Search_Txt";k.setAttribute("type","input");k.setAttribute("placeholder","Search");b(k).keypress(function(a){switch(a.keyCode){case 13:v()}});
var g=document.createElement("div");g.id="TT_Branding";b(g).mouseenter(function(){b(this).addClass("hover")}).mouseleave(function(){b(this).removeClass("hover")}).click(function(){TT_Analytics.log("logo");window.open("YontooClient"in window?"http://www.topictorch.com/settings.aspx":crtinvinfo.url,"TopicTorch")});var j=document.createElement("div");j.id="TT_Related";b(j).width(b(window).width()-305);c.appendChild(k);c.appendChild(o);a.appendChild(d);a.appendChild(e);a.appendChild(c);a.appendChild(g);
a.appendChild(j);document.body.appendChild(a);b(window).resize(function(){b(window).width()<1200?(b(a).hasClass("side")?b(j).width("100%"):b(j).width(b(window).width()-265),b(a).addClass("small")):(b(a).hasClass("side")?b(j).width("100%"):b(j).width(b(window).width()-340),b("#TT_Frame").removeClass("small"));if(b(a).hasClass("side")){var d=b(j);d.height(b(window).height()-parseInt(d.css("top"))-92);d.find("li").each(function(a,e){e=b(e);e.text()!="|"&&(e=b(e).show(),d.height()<e.offset().top+e.height()&&
e.hide())})}})}function g(){var a=b("#TT_Frame"),d={};a.hasClass("left")?d.left=0:a.hasClass("right")?d.right=0:d.bottom=f()?-b(window).scrollTop():0;a.stop().animate(d);h()}function h(a){if(q){if(a)switch(a={},m){case i.LEFT:a["margin-left"]=0;break;case i.RIGHT:a["margin-right"]=0;break;default:a["margin-bottom"]=0}else switch(a={},m){case i.LEFT:a["margin-left"]=b("#TT_Frame").width();break;case i.RIGHT:a["margin-right"]=b("#TT_Frame").width();break;default:a["margin-bottom"]=b("#TT_Frame").height()}b("body").css(a);
p()}}function p(){try{var a;window.navigator.appName.toLowerCase()==="microsoft internet explorer"?(a=document.createEventObject(),a.type="resize",window.document.fireEvent("onresize",a)):(a=document.createEvent("Event"),a.initEvent("resize",!0,!0),window.document.dispatchEvent(a))}catch(b){}}function v(){var a=b("#TT_Search_Txt").val();if(a!=""){var d=encodeURIComponent(r.replace("NETSEERQUERY",a));w(a,"search",0,d)}}function x(a,b){var e=document.createElement("script");if(b)e.addEventListener?
e.addEventListener("load",b,!1):e.onreadystatechange=function(){(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")&&b()};e.src=a;document.getElementsByTagName("head")[0].appendChild(e)}function B(){if(b("#TT_Closed").length==0){CSSRules.add("#TT_Closed","z-index:9999999999; position:fixed; width: 22px; height:27px; background: none repeat scroll 0% 0% rgb(250, 250, 250); border: medium none rgb(250, 250, 250); padding: 0px; margin: 0px; border-radius: 0px 0px 2px 2px; box-shadow: 0px 0px 5px rgb(0, 0, 0); display: block; cursor:pointer;");
CSSRules.add("#TT_Closed",'top:auto;right:5px;bottom:-40px;left:auto; _position:absolute; _bottom:expression(eval(closed ? 40 : 0 - document.body.scrollTop) + "px"); ');CSSRules.add("#TT_ClosedBranding","position:relative; margin:2px auto; width:16px; height:16px; background:url(http://api.topictorch.com/app/img/tt_buttons.png) no-repeat -46px -31px;");CSSRules.add(".side #TT_ClosedBranding","margin:2px; display:inline-block");CSSRules.add("#TT_ClosedArrow","position:relative; margin:2px auto; width:16px; height:5px; background:url(http://api.topictorch.com/app/img/tt_buttons.png) no-repeat -165px -38px");
CSSRules.add("#TT_ClosedArrow.hover","background-position:-190px -38px");CSSRules.add(".side #TT_ClosedArrow","display:none;");var a=document.createElement("div");a.id="TT_Closed";if(b("#TT_Frame").hasClass("slide"))close.className="slide";var d=document.createElement("div");d.id="TT_ClosedBranding";var e=document.createElement("div");e.id="TT_ClosedArrow";a.appendChild(d);a.appendChild(e);b(a).mouseenter(function(){b(e).addClass("hover")}).mouseleave(function(){b(e).removeClass("hover")}).click(function(){var a=
{};a.bottom=$("#TT_Frame").hasClass("side")?-40:f()?-(b(document).scrollTop()+40):-40;b("#TT_Closed").stop().animate(a,"slow");g();h()});document.body.appendChild(a)}a={};a.bottom=$("#TT_Frame").hasClass("side")?0:f()?-b(document).scrollTop():0;b("#TT_Closed").stop().animate(a,"slow")}function t(a){typeof a=="string"||typeof a.childNodes!="undefined"?(typeof a=="string"&&(a=b.parseXML(a)),this.resultType=b(a).find("results-type").text(),this.resultType=="NETSEER"&&C(a)):(this.resultType=a.results["results-type"],
this.resultType=="NETSEER"&&D(a));this.resultType=="NETSEER"?b("#TT_Frame").show():(b("#TT_Frame").remove(),delete TopicTorch);g()}function D(a){var d=a.results.concepts.concept;if(d.length!=0){r=a.results["search-url"];var e=y();b(d).each(function(a,d){var c=z(d.visible,d.clickurl,a);e.appendChild(c);if(b(this).next())c=document.createElement("li"),c.innerHTML="|",c.className="divider",e.appendChild(c)});TT_Analytics.log("contextual added");b("#TT_Related").html(e);p()}}function C(a){var d=b(a).find("concept");
if(b(d).length!=0){r=b(a).find("search-url").text();var e=y();b(d).each(function(a,d){var c=z(b(d).find("visible").text(),b(d).find("clickurl").text().replace(/(\r\n|\n|\r)/gm,""),a);e.appendChild(c);if(b(this).next())c=document.createElement("li"),c.innerHTML="|",c.className="divider",e.appendChild(c)});TT_Analytics.log("contextual added");b("#TT_Related").html(e);p()}}function y(){var a=document.createElement("ul"),b=document.createElement("li");b.innerHTML="Related Searches:";a.appendChild(b);
return a}function z(a,d,e){var c=document.createElement("li"),f=document.createElement("a");f.href="#";f.innerHTML=a;c.appendChild(f);b(f).click(function(a){a.preventDefault();w(b(this).html(),"contextual",e,encodeURIComponent(d))});return c}function w(a,b,c,f){TT_Analytics.log("show serp",b,c);var g=encodeURIComponent(a);if(s)try{var h="//api.yontoo.com/sl/?message=NS_TERMS,{0},{1},{2},{3}".format(b=="contextual"?"click":"search",g,c,TopicTorch.getInstallId);(new Image).src=h}catch(i){}a="http://www.contenko.com/#/?q="+
encodeURIComponent(a)+"&searchTerm="+encodeURIComponent(a)+"&affid=tt&site=-1&guid="+TopicTorch.getInstallId+"&ip="+TopicTorch.getClientIP;f&&(a+="&ad="+f);window.open(a)}var i={BOTTOM:0,LEFT:1,RIGHT:2},b,u,r,s,A,m,q,l;s="YontooClient"in window;A="crtinvinfo"in window;return{POSITIONS:i,process:t,getInstallId:"",getClientIP:"",bid:0,version:2,init:function(a){l=a||{};switch(l.position){case i.LEFT:case i.RIGHT:m=l.position;break;default:m=i.BOTTOM}switch(l.margin){case !0:q=!0;break;default:q=!1}if(s)try{TopicTorch.getClientIP=
YontooClient.getClientIP(),TopicTorch.getInstallId=YontooClient.getInstallId(),TopicTorch.bid=YontooClient.bid}catch(b){}else if(A)try{TopicTorch.getClientIP=crtinvinfo.userId,TopicTorch.getInstallId=crtinvinfo.ip,TopicTorch.bid=crtinvinfo.subId}catch(e){}tlid=15821;x("http://www.google-analytics.com/ga.js");x("http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js",c);TT_Analytics.log("started")}}}();
